/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_PROTOCOL_H_RPCGEN
#define _LOG_PROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "internal.h"
#include "virxdrdefs.h"

typedef char virLogManagerProtocolUUID[VIR_UUID_BUFLEN];
#define VIR_LOG_MANAGER_PROTOCOL_STRING_MAX 4194304

typedef char *virLogManagerProtocolNonNullString;

typedef virLogManagerProtocolNonNullString *virLogManagerProtocolString;

struct virLogManagerProtocolDomain {
        virLogManagerProtocolUUID uuid;
        virLogManagerProtocolNonNullString name;
};
typedef struct virLogManagerProtocolDomain virLogManagerProtocolDomain;


struct virLogManagerProtocolLogFilePosition {
        uint64_t inode;
        uint64_t offset;
};
typedef struct virLogManagerProtocolLogFilePosition virLogManagerProtocolLogFilePosition;


struct virLogManagerProtocolDomainOpenLogFileArgs {
        virLogManagerProtocolNonNullString driver;
        virLogManagerProtocolDomain dom;
        virLogManagerProtocolNonNullString path;
        u_int flags;
};
typedef struct virLogManagerProtocolDomainOpenLogFileArgs virLogManagerProtocolDomainOpenLogFileArgs;

struct virLogManagerProtocolDomainOpenLogFileRet {
        virLogManagerProtocolLogFilePosition pos;
};
typedef struct virLogManagerProtocolDomainOpenLogFileRet virLogManagerProtocolDomainOpenLogFileRet;

struct virLogManagerProtocolDomainGetLogFilePositionArgs {
        virLogManagerProtocolNonNullString path;
        u_int flags;
};
typedef struct virLogManagerProtocolDomainGetLogFilePositionArgs virLogManagerProtocolDomainGetLogFilePositionArgs;

struct virLogManagerProtocolDomainGetLogFilePositionRet {
        virLogManagerProtocolLogFilePosition pos;
};
typedef struct virLogManagerProtocolDomainGetLogFilePositionRet virLogManagerProtocolDomainGetLogFilePositionRet;

struct virLogManagerProtocolDomainReadLogFileArgs {
        virLogManagerProtocolNonNullString path;
        virLogManagerProtocolLogFilePosition pos;
        uint64_t maxlen;
        u_int flags;
};
typedef struct virLogManagerProtocolDomainReadLogFileArgs virLogManagerProtocolDomainReadLogFileArgs;

struct virLogManagerProtocolDomainReadLogFileRet {
        virLogManagerProtocolNonNullString data;
};
typedef struct virLogManagerProtocolDomainReadLogFileRet virLogManagerProtocolDomainReadLogFileRet;
#define VIR_LOG_MANAGER_PROTOCOL_PROGRAM 0x87539319
#define VIR_LOG_MANAGER_PROTOCOL_PROGRAM_VERSION 1

enum virLogManagerProtocolProcedure {
        VIR_LOG_MANAGER_PROTOCOL_PROC_DOMAIN_OPEN_LOG_FILE = 1,
        VIR_LOG_MANAGER_PROTOCOL_PROC_DOMAIN_GET_LOG_FILE_POSITION = 2,
        VIR_LOG_MANAGER_PROTOCOL_PROC_DOMAIN_READ_LOG_FILE = 3,
};
typedef enum virLogManagerProtocolProcedure virLogManagerProtocolProcedure;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_virLogManagerProtocolUUID (XDR *, virLogManagerProtocolUUID);
extern  bool_t xdr_virLogManagerProtocolNonNullString (XDR *, virLogManagerProtocolNonNullString*);
extern  bool_t xdr_virLogManagerProtocolString (XDR *, virLogManagerProtocolString*);
extern  bool_t xdr_virLogManagerProtocolDomain (XDR *, virLogManagerProtocolDomain*);
extern  bool_t xdr_virLogManagerProtocolDomain (XDR *, virLogManagerProtocolDomain*);
extern  bool_t xdr_virLogManagerProtocolLogFilePosition (XDR *, virLogManagerProtocolLogFilePosition*);
extern  bool_t xdr_virLogManagerProtocolLogFilePosition (XDR *, virLogManagerProtocolLogFilePosition*);
extern  bool_t xdr_virLogManagerProtocolDomainOpenLogFileArgs (XDR *, virLogManagerProtocolDomainOpenLogFileArgs*);
extern  bool_t xdr_virLogManagerProtocolDomainOpenLogFileRet (XDR *, virLogManagerProtocolDomainOpenLogFileRet*);
extern  bool_t xdr_virLogManagerProtocolDomainGetLogFilePositionArgs (XDR *, virLogManagerProtocolDomainGetLogFilePositionArgs*);
extern  bool_t xdr_virLogManagerProtocolDomainGetLogFilePositionRet (XDR *, virLogManagerProtocolDomainGetLogFilePositionRet*);
extern  bool_t xdr_virLogManagerProtocolDomainReadLogFileArgs (XDR *, virLogManagerProtocolDomainReadLogFileArgs*);
extern  bool_t xdr_virLogManagerProtocolDomainReadLogFileRet (XDR *, virLogManagerProtocolDomainReadLogFileRet*);
extern  bool_t xdr_virLogManagerProtocolProcedure (XDR *, virLogManagerProtocolProcedure*);

#else /* K&R C */
extern bool_t xdr_virLogManagerProtocolUUID ();
extern bool_t xdr_virLogManagerProtocolNonNullString ();
extern bool_t xdr_virLogManagerProtocolString ();
extern bool_t xdr_virLogManagerProtocolDomain ();
extern bool_t xdr_virLogManagerProtocolDomain ();
extern bool_t xdr_virLogManagerProtocolLogFilePosition ();
extern bool_t xdr_virLogManagerProtocolLogFilePosition ();
extern bool_t xdr_virLogManagerProtocolDomainOpenLogFileArgs ();
extern bool_t xdr_virLogManagerProtocolDomainOpenLogFileRet ();
extern bool_t xdr_virLogManagerProtocolDomainGetLogFilePositionArgs ();
extern bool_t xdr_virLogManagerProtocolDomainGetLogFilePositionRet ();
extern bool_t xdr_virLogManagerProtocolDomainReadLogFileArgs ();
extern bool_t xdr_virLogManagerProtocolDomainReadLogFileRet ();
extern bool_t xdr_virLogManagerProtocolProcedure ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_PROTOCOL_H_RPCGEN */
