/* Generated by esx_vi_generator.py */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: ManagedEntityStatus
 */

static const esxVI_Enumeration _esxVI_ManagedEntityStatus_Enumeration = {
    esxVI_Type_ManagedEntityStatus, {
        { "gray", esxVI_ManagedEntityStatus_Gray },
        { "green", esxVI_ManagedEntityStatus_Green },
        { "yellow", esxVI_ManagedEntityStatus_Yellow },
        { "red", esxVI_ManagedEntityStatus_Red },
        { NULL, -1 },
    },
};

/* esxVI_ManagedEntityStatus_CastFromAnyType */
ESX_VI__TEMPLATE__ENUMERATION__CAST_FROM_ANY_TYPE(ManagedEntityStatus)

/* esxVI_ManagedEntityStatus_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(ManagedEntityStatus)

/* esxVI_ManagedEntityStatus_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(ManagedEntityStatus)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: ObjectUpdateKind
 */

static const esxVI_Enumeration _esxVI_ObjectUpdateKind_Enumeration = {
    esxVI_Type_ObjectUpdateKind, {
        { "modify", esxVI_ObjectUpdateKind_Modify },
        { "enter", esxVI_ObjectUpdateKind_Enter },
        { "leave", esxVI_ObjectUpdateKind_Leave },
        { NULL, -1 },
    },
};

/* esxVI_ObjectUpdateKind_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(ObjectUpdateKind)

/* esxVI_ObjectUpdateKind_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(ObjectUpdateKind)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: PerfStatsType
 */

static const esxVI_Enumeration _esxVI_PerfStatsType_Enumeration = {
    esxVI_Type_PerfStatsType, {
        { "absolute", esxVI_PerfStatsType_Absolute },
        { "delta", esxVI_PerfStatsType_Delta },
        { "rate", esxVI_PerfStatsType_Rate },
        { NULL, -1 },
    },
};

/* esxVI_PerfStatsType_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(PerfStatsType)

/* esxVI_PerfStatsType_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(PerfStatsType)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: PerfSummaryType
 */

static const esxVI_Enumeration _esxVI_PerfSummaryType_Enumeration = {
    esxVI_Type_PerfSummaryType, {
        { "average", esxVI_PerfSummaryType_Average },
        { "maximum", esxVI_PerfSummaryType_Maximum },
        { "minimum", esxVI_PerfSummaryType_Minimum },
        { "latest", esxVI_PerfSummaryType_Latest },
        { "summation", esxVI_PerfSummaryType_Summation },
        { "none", esxVI_PerfSummaryType_None },
        { NULL, -1 },
    },
};

/* esxVI_PerfSummaryType_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(PerfSummaryType)

/* esxVI_PerfSummaryType_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(PerfSummaryType)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: PropertyChangeOp
 */

static const esxVI_Enumeration _esxVI_PropertyChangeOp_Enumeration = {
    esxVI_Type_PropertyChangeOp, {
        { "add", esxVI_PropertyChangeOp_Add },
        { "remove", esxVI_PropertyChangeOp_Remove },
        { "assign", esxVI_PropertyChangeOp_Assign },
        { "indirectRemove", esxVI_PropertyChangeOp_IndirectRemove },
        { NULL, -1 },
    },
};

/* esxVI_PropertyChangeOp_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(PropertyChangeOp)

/* esxVI_PropertyChangeOp_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(PropertyChangeOp)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: SharesLevel
 */

static const esxVI_Enumeration _esxVI_SharesLevel_Enumeration = {
    esxVI_Type_SharesLevel, {
        { "low", esxVI_SharesLevel_Low },
        { "normal", esxVI_SharesLevel_Normal },
        { "high", esxVI_SharesLevel_High },
        { "custom", esxVI_SharesLevel_Custom },
        { NULL, -1 },
    },
};

/* esxVI_SharesLevel_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(SharesLevel)

/* esxVI_SharesLevel_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(SharesLevel)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: TaskInfoState
 */

static const esxVI_Enumeration _esxVI_TaskInfoState_Enumeration = {
    esxVI_Type_TaskInfoState, {
        { "queued", esxVI_TaskInfoState_Queued },
        { "running", esxVI_TaskInfoState_Running },
        { "success", esxVI_TaskInfoState_Success },
        { "error", esxVI_TaskInfoState_Error },
        { NULL, -1 },
    },
};

/* esxVI_TaskInfoState_CastFromAnyType */
ESX_VI__TEMPLATE__ENUMERATION__CAST_FROM_ANY_TYPE(TaskInfoState)

/* esxVI_TaskInfoState_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(TaskInfoState)

/* esxVI_TaskInfoState_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(TaskInfoState)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: VirtualMachineMovePriority
 */

static const esxVI_Enumeration _esxVI_VirtualMachineMovePriority_Enumeration = {
    esxVI_Type_VirtualMachineMovePriority, {
        { "lowPriority", esxVI_VirtualMachineMovePriority_LowPriority },
        { "highPriority", esxVI_VirtualMachineMovePriority_HighPriority },
        { "defaultPriority", esxVI_VirtualMachineMovePriority_DefaultPriority },
        { NULL, -1 },
    },
};

/* esxVI_VirtualMachineMovePriority_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(VirtualMachineMovePriority)

/* esxVI_VirtualMachineMovePriority_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(VirtualMachineMovePriority)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Enum: VirtualMachinePowerState
 */

static const esxVI_Enumeration _esxVI_VirtualMachinePowerState_Enumeration = {
    esxVI_Type_VirtualMachinePowerState, {
        { "poweredOff", esxVI_VirtualMachinePowerState_PoweredOff },
        { "poweredOn", esxVI_VirtualMachinePowerState_PoweredOn },
        { "suspended", esxVI_VirtualMachinePowerState_Suspended },
        { NULL, -1 },
    },
};

/* esxVI_VirtualMachinePowerState_CastFromAnyType */
ESX_VI__TEMPLATE__ENUMERATION__CAST_FROM_ANY_TYPE(VirtualMachinePowerState)

/* esxVI_VirtualMachinePowerState_Serialize */
ESX_VI__TEMPLATE__ENUMERATION__SERIALIZE(VirtualMachinePowerState)

/* esxVI_VirtualMachinePowerState_Deserialize */
ESX_VI__TEMPLATE__ENUMERATION__DESERIALIZE(VirtualMachinePowerState)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: AboutInfo
 */

/* esxVI_AboutInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(AboutInfo)

/* esxVI_AboutInfo_Free */
ESX_VI__TEMPLATE__FREE(AboutInfo,
{
    VIR_FREE(item->name);
    VIR_FREE(item->fullName);
    VIR_FREE(item->vendor);
    VIR_FREE(item->version);
    VIR_FREE(item->build);
    VIR_FREE(item->localeVersion);
    VIR_FREE(item->localeBuild);
    VIR_FREE(item->osType);
    VIR_FREE(item->productLineId);
    VIR_FREE(item->apiType);
    VIR_FREE(item->apiVersion);
})

/* esxVI_AboutInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(AboutInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(fullName)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(vendor)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(version)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(build)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(osType)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(productLineId)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(apiType)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(apiVersion)
})

/* esxVI_AboutInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(AboutInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, fullName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, vendor)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, build)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, localeVersion)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, localeBuild)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, osType)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, productLineId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, apiType)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, apiVersion)
})

/* esxVI_AboutInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(AboutInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, fullName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, vendor)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, build)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, localeVersion)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, localeBuild)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, osType)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, productLineId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, apiType)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, apiVersion)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ChoiceOption
 *          extends OptionType
 */

/* esxVI_ChoiceOption_Alloc */
ESX_VI__TEMPLATE__ALLOC(ChoiceOption)

/* esxVI_ChoiceOption_Free */
ESX_VI__TEMPLATE__FREE(ChoiceOption,
{
    /* OptionType */
    /* no properties to be freed */

    /* ChoiceOption */
    esxVI_ElementDescription_Free(&item->choiceInfo);
    esxVI_Int_Free(&item->defaultIndex);
})

/* esxVI_ChoiceOption_Validate */
ESX_VI__TEMPLATE__VALIDATE(ChoiceOption,
{
    /* OptionType */
    /* no required properties */

    /* ChoiceOption */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(choiceInfo)
})

/* esxVI_ChoiceOption_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(ChoiceOption,
{
    /* OptionType */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, valueIsReadonly)

    /* ChoiceOption */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(ElementDescription, choiceInfo)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, defaultIndex)
})

/* esxVI_ChoiceOption_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ChoiceOption,
{
    /* OptionType */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, valueIsReadonly)

    /* ChoiceOption */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(ElementDescription, choiceInfo)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, defaultIndex)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: DatastoreInfo
 *          extended by LocalDatastoreInfo
 *                      NasDatastoreInfo
 *                      VmfsDatastoreInfo
 */

/* esxVI_DatastoreInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(DatastoreInfo)

/* esxVI_DatastoreInfo_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(DatastoreInfo,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(LocalDatastoreInfo)
    ESX_VI__TEMPLATE__DISPATCH__FREE(NasDatastoreInfo)
    ESX_VI__TEMPLATE__DISPATCH__FREE(VmfsDatastoreInfo)
},
{
    VIR_FREE(item->name);
    VIR_FREE(item->url);
    esxVI_Long_Free(&item->freeSpace);
    esxVI_Long_Free(&item->maxFileSize);
})

/* esxVI_DatastoreInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(DatastoreInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(url)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(maxFileSize)
})

/* esxVI_DatastoreInfo_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(DatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__DYNAMIC_CAST__ACCEPT(LocalDatastoreInfo)
    ESX_VI__TEMPLATE__DYNAMIC_CAST__ACCEPT(NasDatastoreInfo)
    ESX_VI__TEMPLATE__DYNAMIC_CAST__ACCEPT(VmfsDatastoreInfo)
})

/* esxVI_DatastoreInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(DatastoreInfo,
{
    ESX_VI__TEMPLATE__DISPATCH__CAST_FROM_ANY_TYPE(LocalDatastoreInfo)
    ESX_VI__TEMPLATE__DISPATCH__CAST_FROM_ANY_TYPE(NasDatastoreInfo)
    ESX_VI__TEMPLATE__DISPATCH__CAST_FROM_ANY_TYPE(VmfsDatastoreInfo)
})

/* esxVI_DatastoreInfo_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(DatastoreInfo,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(LocalDatastoreInfo)
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(NasDatastoreInfo)
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(VmfsDatastoreInfo)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, maxFileSize)
})

/* esxVI_DatastoreInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(DatastoreInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, maxFileSize)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: Description
 *          extended by ElementDescription
 */

/* esxVI_Description_Alloc */
ESX_VI__TEMPLATE__ALLOC(Description)

/* esxVI_Description_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(Description,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(ElementDescription)
},
{
    esxVI_Description_Free(&item->_next);

    VIR_FREE(item->label);
    VIR_FREE(item->summary);
})

/* esxVI_Description_Validate */
ESX_VI__TEMPLATE__VALIDATE(Description,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(label)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(summary)
})

/* esxVI_Description_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(Description)

/* esxVI_Description_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(Description,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(ElementDescription)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, label)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, summary)
})

/* esxVI_Description_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(Description)

/* esxVI_Description_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(Description,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, label)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, summary)
})

/* esxVI_Description_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(Description)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: DynamicProperty
 */

/* esxVI_DynamicProperty_Alloc */
ESX_VI__TEMPLATE__ALLOC(DynamicProperty)

/* esxVI_DynamicProperty_Free */
ESX_VI__TEMPLATE__FREE(DynamicProperty,
{
    esxVI_DynamicProperty_Free(&item->_next);

    VIR_FREE(item->name);
    esxVI_AnyType_Free(&item->val);
})

/* esxVI_DynamicProperty_Validate */
ESX_VI__TEMPLATE__VALIDATE(DynamicProperty,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(val)
})

/* esxVI_DynamicProperty_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(DynamicProperty)

/* esxVI_DynamicProperty_DeepCopy */
ESX_VI__TEMPLATE__DEEP_COPY(DynamicProperty,
{
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY(AnyType, val)
})

/* esxVI_DynamicProperty_DeepCopyList */
ESX_VI__TEMPLATE__LIST__DEEP_COPY(DynamicProperty)

/* esxVI_DynamicProperty_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(DynamicProperty,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(AnyType, val)
})

/* esxVI_DynamicProperty_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(DynamicProperty)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ElementDescription
 *          extends Description
 */

/* esxVI_ElementDescription_Alloc */
ESX_VI__TEMPLATE__ALLOC(ElementDescription)

/* esxVI_ElementDescription_Free */
ESX_VI__TEMPLATE__FREE(ElementDescription,
{
    esxVI_ElementDescription_Free(&item->_next);

    /* Description */
    VIR_FREE(item->label);
    VIR_FREE(item->summary);

    /* ElementDescription */
    VIR_FREE(item->key);
})

/* esxVI_ElementDescription_Validate */
ESX_VI__TEMPLATE__VALIDATE(ElementDescription,
{
    /* Description */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(label)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(summary)

    /* ElementDescription */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(key)
})

/* esxVI_ElementDescription_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(ElementDescription)

/* esxVI_ElementDescription_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(ElementDescription,
{
    /* Description */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, label)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, summary)

    /* ElementDescription */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, key)
})

/* esxVI_ElementDescription_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(ElementDescription)

/* esxVI_ElementDescription_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ElementDescription,
{
    /* Description */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, label)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, summary)

    /* ElementDescription */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, key)
})

/* esxVI_ElementDescription_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(ElementDescription)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: Event
 */

/* esxVI_Event_Alloc */
ESX_VI__TEMPLATE__ALLOC(Event)

/* esxVI_Event_Free */
ESX_VI__TEMPLATE__FREE(Event,
{
    esxVI_Event_Free(&item->_next);

    esxVI_Int_Free(&item->key);
    esxVI_Int_Free(&item->chainId);
    esxVI_DateTime_Free(&item->createdTime);
    VIR_FREE(item->userName);
    /* FIXME: datacenter is currently ignored */
    /* FIXME: computeResource is currently ignored */
    /* FIXME: host is currently ignored */
    /* FIXME: vm is currently ignored */
    VIR_FREE(item->fullFormattedMessage);
})

/* esxVI_Event_Validate */
ESX_VI__TEMPLATE__VALIDATE(Event,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(key)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(chainId)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(createdTime)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(userName)
    /* FIXME: datacenter is currently ignored */
    /* FIXME: computeResource is currently ignored */
    /* FIXME: host is currently ignored */
    /* FIXME: vm is currently ignored */
})

/* esxVI_Event_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(Event)

/* esxVI_Event_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(Event,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, key)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, chainId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(DateTime, createdTime)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, userName)
    /* FIXME: datacenter is currently ignored */
    /* FIXME: computeResource is currently ignored */
    /* FIXME: host is currently ignored */
    /* FIXME: vm is currently ignored */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, fullFormattedMessage)
})

/* esxVI_Event_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(Event)

/* esxVI_Event_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(Event,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, key)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, chainId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, createdTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, userName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(datacenter) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(computeResource) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(host) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(vm) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, fullFormattedMessage)
})

/* esxVI_Event_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(Event)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: HostCpuIdInfo
 */

/* esxVI_HostCpuIdInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(HostCpuIdInfo)

/* esxVI_HostCpuIdInfo_Free */
ESX_VI__TEMPLATE__FREE(HostCpuIdInfo,
{
    esxVI_HostCpuIdInfo_Free(&item->_next);

    esxVI_Int_Free(&item->level);
    VIR_FREE(item->vendor);
    VIR_FREE(item->eax);
    VIR_FREE(item->ebx);
    VIR_FREE(item->ecx);
    VIR_FREE(item->edx);
})

/* esxVI_HostCpuIdInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(HostCpuIdInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(level)
})

/* esxVI_HostCpuIdInfo_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(HostCpuIdInfo)

/* esxVI_HostCpuIdInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(HostCpuIdInfo,
{
})

/* esxVI_HostCpuIdInfo_CastListFromAnyType */
ESX_VI__TEMPLATE__LIST__CAST_FROM_ANY_TYPE(HostCpuIdInfo)

/* esxVI_HostCpuIdInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(HostCpuIdInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, level)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, vendor)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, eax)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, ebx)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, ecx)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, edx)
})

/* esxVI_HostCpuIdInfo_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(HostCpuIdInfo)

/* esxVI_HostCpuIdInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(HostCpuIdInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, level)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, vendor)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, eax)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, ebx)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, ecx)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, edx)
})

/* esxVI_HostCpuIdInfo_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(HostCpuIdInfo)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: HostFileSystemVolume
 *          extended by HostNasVolume
 *                      HostVmfsVolume
 */

/* esxVI_HostFileSystemVolume_Alloc */
ESX_VI__TEMPLATE__ALLOC(HostFileSystemVolume)

/* esxVI_HostFileSystemVolume_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(HostFileSystemVolume,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(HostNasVolume)
    ESX_VI__TEMPLATE__DISPATCH__FREE(HostVmfsVolume)
},
{
    VIR_FREE(item->type);
    VIR_FREE(item->name);
    esxVI_Long_Free(&item->capacity);
})

/* esxVI_HostFileSystemVolume_Validate */
ESX_VI__TEMPLATE__VALIDATE(HostFileSystemVolume,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(type)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(capacity)
})

/* esxVI_HostFileSystemVolume_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(HostFileSystemVolume,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(HostNasVolume)
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(HostVmfsVolume)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, capacity)
})

/* esxVI_HostFileSystemVolume_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(HostFileSystemVolume,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, capacity)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: HostNasVolume
 *          extends HostFileSystemVolume
 */

/* esxVI_HostNasVolume_Alloc */
ESX_VI__TEMPLATE__ALLOC(HostNasVolume)

/* esxVI_HostNasVolume_Free */
ESX_VI__TEMPLATE__FREE(HostNasVolume,
{
    /* HostFileSystemVolume */
    VIR_FREE(item->type);
    VIR_FREE(item->name);
    esxVI_Long_Free(&item->capacity);

    /* HostNasVolume */
    VIR_FREE(item->remoteHost);
    VIR_FREE(item->remotePath);
    VIR_FREE(item->userName);
})

/* esxVI_HostNasVolume_Validate */
ESX_VI__TEMPLATE__VALIDATE(HostNasVolume,
{
    /* HostFileSystemVolume */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(type)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(capacity)

    /* HostNasVolume */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(remoteHost)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(remotePath)
})

/* esxVI_HostNasVolume_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(HostNasVolume,
{
    /* HostFileSystemVolume */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, capacity)

    /* HostNasVolume */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, remoteHost)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, remotePath)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, userName)
})

/* esxVI_HostNasVolume_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(HostNasVolume,
{
    /* HostFileSystemVolume */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, capacity)

    /* HostNasVolume */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, remoteHost)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, remotePath)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, userName)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: HostScsiDiskPartition
 */

/* esxVI_HostScsiDiskPartition_Alloc */
ESX_VI__TEMPLATE__ALLOC(HostScsiDiskPartition)

/* esxVI_HostScsiDiskPartition_Free */
ESX_VI__TEMPLATE__FREE(HostScsiDiskPartition,
{
    esxVI_HostScsiDiskPartition_Free(&item->_next);

    VIR_FREE(item->diskName);
    esxVI_Int_Free(&item->partition);
})

/* esxVI_HostScsiDiskPartition_Validate */
ESX_VI__TEMPLATE__VALIDATE(HostScsiDiskPartition,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(diskName)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(partition)
})

/* esxVI_HostScsiDiskPartition_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(HostScsiDiskPartition)

/* esxVI_HostScsiDiskPartition_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(HostScsiDiskPartition,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, diskName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, partition)
})

/* esxVI_HostScsiDiskPartition_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(HostScsiDiskPartition)

/* esxVI_HostScsiDiskPartition_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(HostScsiDiskPartition,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, diskName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, partition)
})

/* esxVI_HostScsiDiskPartition_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(HostScsiDiskPartition)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: HostVmfsVolume
 *          extends HostFileSystemVolume
 */

/* esxVI_HostVmfsVolume_Alloc */
ESX_VI__TEMPLATE__ALLOC(HostVmfsVolume)

/* esxVI_HostVmfsVolume_Free */
ESX_VI__TEMPLATE__FREE(HostVmfsVolume,
{
    /* HostFileSystemVolume */
    VIR_FREE(item->type);
    VIR_FREE(item->name);
    esxVI_Long_Free(&item->capacity);

    /* HostVmfsVolume */
    esxVI_Int_Free(&item->blockSizeMb);
    esxVI_Int_Free(&item->maxBlocks);
    esxVI_Int_Free(&item->majorVersion);
    VIR_FREE(item->version);
    VIR_FREE(item->uuid);
    esxVI_HostScsiDiskPartition_Free(&item->extent);
})

/* esxVI_HostVmfsVolume_Validate */
ESX_VI__TEMPLATE__VALIDATE(HostVmfsVolume,
{
    /* HostFileSystemVolume */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(type)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(capacity)

    /* HostVmfsVolume */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(blockSizeMb)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(maxBlocks)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(majorVersion)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(version)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(uuid)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(extent)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(vmfsUpgradable)
})

/* esxVI_HostVmfsVolume_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(HostVmfsVolume,
{
    /* HostFileSystemVolume */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, capacity)

    /* HostVmfsVolume */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, blockSizeMb)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, maxBlocks)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, majorVersion)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, uuid)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(HostScsiDiskPartition, extent)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, vmfsUpgradable)
})

/* esxVI_HostVmfsVolume_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(HostVmfsVolume,
{
    /* HostFileSystemVolume */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, capacity)

    /* HostVmfsVolume */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, blockSizeMb)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, maxBlocks)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, majorVersion)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, uuid)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(HostScsiDiskPartition, extent)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, vmfsUpgradable)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: LocalDatastoreInfo
 *          extends DatastoreInfo
 */

/* esxVI_LocalDatastoreInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(LocalDatastoreInfo)

/* esxVI_LocalDatastoreInfo_Free */
ESX_VI__TEMPLATE__FREE(LocalDatastoreInfo,
{
    /* DatastoreInfo */
    VIR_FREE(item->name);
    VIR_FREE(item->url);
    esxVI_Long_Free(&item->freeSpace);
    esxVI_Long_Free(&item->maxFileSize);

    /* LocalDatastoreInfo */
    VIR_FREE(item->path);
})

/* esxVI_LocalDatastoreInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(LocalDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(url)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(maxFileSize)

    /* LocalDatastoreInfo */
    /* no required properties */
})

/* esxVI_LocalDatastoreInfo_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(LocalDatastoreInfo,
{
})

/* esxVI_LocalDatastoreInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(LocalDatastoreInfo,
{
})

/* esxVI_LocalDatastoreInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(LocalDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, maxFileSize)

    /* LocalDatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, path)
})

/* esxVI_LocalDatastoreInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(LocalDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, maxFileSize)

    /* LocalDatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, path)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: NasDatastoreInfo
 *          extends DatastoreInfo
 */

/* esxVI_NasDatastoreInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(NasDatastoreInfo)

/* esxVI_NasDatastoreInfo_Free */
ESX_VI__TEMPLATE__FREE(NasDatastoreInfo,
{
    /* DatastoreInfo */
    VIR_FREE(item->name);
    VIR_FREE(item->url);
    esxVI_Long_Free(&item->freeSpace);
    esxVI_Long_Free(&item->maxFileSize);

    /* NasDatastoreInfo */
    esxVI_HostNasVolume_Free(&item->nas);
})

/* esxVI_NasDatastoreInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(NasDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(url)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(maxFileSize)

    /* NasDatastoreInfo */
    /* no required properties */
})

/* esxVI_NasDatastoreInfo_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(NasDatastoreInfo,
{
})

/* esxVI_NasDatastoreInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(NasDatastoreInfo,
{
})

/* esxVI_NasDatastoreInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(NasDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, maxFileSize)

    /* NasDatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(HostNasVolume, nas)
})

/* esxVI_NasDatastoreInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(NasDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, maxFileSize)

    /* NasDatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(HostNasVolume, nas)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ObjectContent
 */

/* esxVI_ObjectContent_Alloc */
ESX_VI__TEMPLATE__ALLOC(ObjectContent)

/* esxVI_ObjectContent_Free */
ESX_VI__TEMPLATE__FREE(ObjectContent,
{
    esxVI_ObjectContent_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->obj);
    esxVI_DynamicProperty_Free(&item->propSet);
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_ObjectContent_Validate */
ESX_VI__TEMPLATE__VALIDATE(ObjectContent,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(obj)
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_ObjectContent_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(ObjectContent)

/* esxVI_ObjectContent_DeepCopy */
ESX_VI__TEMPLATE__DEEP_COPY(ObjectContent,
{
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY(ManagedObjectReference, obj)
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY_LIST(DynamicProperty, propSet)
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_ObjectContent_DeepCopyList */
ESX_VI__TEMPLATE__LIST__DEEP_COPY(ObjectContent)

/* esxVI_ObjectContent_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ObjectContent,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, obj)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(DynamicProperty, propSet)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(missingSet) /* FIXME */
})

/* esxVI_ObjectContent_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(ObjectContent)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ObjectSpec
 */

/* esxVI_ObjectSpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(ObjectSpec)

/* esxVI_ObjectSpec_Free */
ESX_VI__TEMPLATE__FREE(ObjectSpec,
{
    esxVI_ObjectSpec_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->obj);
    esxVI_SelectionSpec_Free(&item->selectSet);
})

/* esxVI_ObjectSpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(ObjectSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(obj)
})

/* esxVI_ObjectSpec_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(ObjectSpec)

/* esxVI_ObjectSpec_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(ObjectSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, obj)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, skip)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(SelectionSpec, selectSet)
})

/* esxVI_ObjectSpec_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(ObjectSpec)

/* esxVI_ObjectSpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ObjectSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, obj)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, skip)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(SelectionSpec, selectSet)
})

/* esxVI_ObjectSpec_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(ObjectSpec)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ObjectUpdate
 */

/* esxVI_ObjectUpdate_Alloc */
ESX_VI__TEMPLATE__ALLOC(ObjectUpdate)

/* esxVI_ObjectUpdate_Free */
ESX_VI__TEMPLATE__FREE(ObjectUpdate,
{
    esxVI_ObjectUpdate_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->obj);
    esxVI_PropertyChange_Free(&item->changeSet);
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_ObjectUpdate_Validate */
ESX_VI__TEMPLATE__VALIDATE(ObjectUpdate,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(kind)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(obj)
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_ObjectUpdate_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(ObjectUpdate)

/* esxVI_ObjectUpdate_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ObjectUpdate,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ObjectUpdateKind, kind)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, obj)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(PropertyChange, changeSet)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(missingSet) /* FIXME */
})

/* esxVI_ObjectUpdate_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(ObjectUpdate)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: OptionType
 *          extended by ChoiceOption
 */

/* esxVI_OptionType_Alloc */
ESX_VI__TEMPLATE__ALLOC(OptionType)

/* esxVI_OptionType_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(OptionType,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(ChoiceOption)
},
{
    /* no properties to be freed */
})

/* esxVI_OptionType_Validate */
ESX_VI__TEMPLATE__VALIDATE(OptionType,
{
    /* no required properties */
})

/* esxVI_OptionType_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(OptionType,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(ChoiceOption)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, valueIsReadonly)
})

/* esxVI_OptionType_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(OptionType,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, valueIsReadonly)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfCounterInfo
 */

/* esxVI_PerfCounterInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfCounterInfo)

/* esxVI_PerfCounterInfo_Free */
ESX_VI__TEMPLATE__FREE(PerfCounterInfo,
{
    esxVI_PerfCounterInfo_Free(&item->_next);

    esxVI_Int_Free(&item->key);
    esxVI_ElementDescription_Free(&item->nameInfo);
    esxVI_ElementDescription_Free(&item->groupInfo);
    esxVI_ElementDescription_Free(&item->unitInfo);
    esxVI_Int_Free(&item->level);
    esxVI_Int_Free(&item->associatedCounterId);
})

/* esxVI_PerfCounterInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfCounterInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(key)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(nameInfo)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(groupInfo)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(unitInfo)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(rollupType)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(statsType)
})

/* esxVI_PerfCounterInfo_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfCounterInfo)

/* esxVI_PerfCounterInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PerfCounterInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, key)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ElementDescription, nameInfo)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ElementDescription, groupInfo)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ElementDescription, unitInfo)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(PerfSummaryType, rollupType)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(PerfStatsType, statsType)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, level)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(Int, associatedCounterId)
})

/* esxVI_PerfCounterInfo_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfCounterInfo)

/* esxVI_PerfCounterInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfCounterInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, key)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ElementDescription, nameInfo)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ElementDescription, groupInfo)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ElementDescription, unitInfo)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(PerfSummaryType, rollupType)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(PerfStatsType, statsType)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, level)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(Int, associatedCounterId)
})

/* esxVI_PerfCounterInfo_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfCounterInfo)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfEntityMetric
 *          extends PerfEntityMetricBase
 */

/* esxVI_PerfEntityMetric_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfEntityMetric)

/* esxVI_PerfEntityMetric_Free */
ESX_VI__TEMPLATE__FREE(PerfEntityMetric,
{
    esxVI_PerfEntityMetric_Free(&item->_next);

    /* PerfEntityMetricBase */
    esxVI_ManagedObjectReference_Free(&item->entity);

    /* PerfEntityMetric */
    esxVI_PerfSampleInfo_Free(&item->sampleInfo);
    esxVI_PerfMetricSeries_Free(&item->value);
})

/* esxVI_PerfEntityMetric_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfEntityMetric,
{
    /* PerfEntityMetricBase */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(entity)

    /* PerfEntityMetric */
    /* no required properties */
})

/* esxVI_PerfEntityMetric_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(PerfEntityMetric,
{
})

/* esxVI_PerfEntityMetric_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfEntityMetric)

/* esxVI_PerfEntityMetric_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PerfEntityMetric,
{
    /* PerfEntityMetricBase */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, entity)

    /* PerfEntityMetric */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(PerfSampleInfo, sampleInfo)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(PerfMetricSeries, value)
})

/* esxVI_PerfEntityMetric_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfEntityMetric)

/* esxVI_PerfEntityMetric_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfEntityMetric,
{
    /* PerfEntityMetricBase */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, entity)

    /* PerfEntityMetric */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(PerfSampleInfo, sampleInfo)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(PerfMetricSeries, value)
})

/* esxVI_PerfEntityMetric_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfEntityMetric)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfEntityMetricBase
 *          extended by PerfEntityMetric
 */

/* esxVI_PerfEntityMetricBase_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfEntityMetricBase)

/* esxVI_PerfEntityMetricBase_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(PerfEntityMetricBase,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(PerfEntityMetric)
},
{
    esxVI_PerfEntityMetricBase_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->entity);
})

/* esxVI_PerfEntityMetricBase_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfEntityMetricBase,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(entity)
})

/* esxVI_PerfEntityMetricBase_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(PerfEntityMetricBase,
{
    /* PerfEntityMetricBase */
    ESX_VI__TEMPLATE__DYNAMIC_CAST__ACCEPT(PerfEntityMetric)
})

/* esxVI_PerfEntityMetricBase_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfEntityMetricBase)

/* esxVI_PerfEntityMetricBase_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(PerfEntityMetricBase,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(PerfEntityMetric)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, entity)
})

/* esxVI_PerfEntityMetricBase_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfEntityMetricBase)

/* esxVI_PerfEntityMetricBase_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfEntityMetricBase,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, entity)
})

/* esxVI_PerfEntityMetricBase_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfEntityMetricBase)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfMetricId
 */

/* esxVI_PerfMetricId_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfMetricId)

/* esxVI_PerfMetricId_Free */
ESX_VI__TEMPLATE__FREE(PerfMetricId,
{
    esxVI_PerfMetricId_Free(&item->_next);

    esxVI_Int_Free(&item->counterId);
    VIR_FREE(item->instance);
})

/* esxVI_PerfMetricId_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfMetricId,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(counterId)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(instance)
})

/* esxVI_PerfMetricId_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfMetricId)

/* esxVI_PerfMetricId_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PerfMetricId,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, counterId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, instance)
})

/* esxVI_PerfMetricId_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfMetricId)

/* esxVI_PerfMetricId_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfMetricId,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, counterId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, instance)
})

/* esxVI_PerfMetricId_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfMetricId)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfMetricIntSeries
 *          extends PerfMetricSeries
 */

/* esxVI_PerfMetricIntSeries_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfMetricIntSeries)

/* esxVI_PerfMetricIntSeries_Free */
ESX_VI__TEMPLATE__FREE(PerfMetricIntSeries,
{
    esxVI_PerfMetricIntSeries_Free(&item->_next);

    /* PerfMetricSeries */
    esxVI_PerfMetricId_Free(&item->id);

    /* PerfMetricIntSeries */
    esxVI_Long_Free(&item->value);
})

/* esxVI_PerfMetricIntSeries_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfMetricIntSeries,
{
    /* PerfMetricSeries */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(id)

    /* PerfMetricIntSeries */
    /* no required properties */
})

/* esxVI_PerfMetricIntSeries_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(PerfMetricIntSeries,
{
})

/* esxVI_PerfMetricIntSeries_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfMetricIntSeries)

/* esxVI_PerfMetricIntSeries_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PerfMetricIntSeries,
{
    /* PerfMetricSeries */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(PerfMetricId, id)

    /* PerfMetricIntSeries */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(Long, value)
})

/* esxVI_PerfMetricIntSeries_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfMetricIntSeries)

/* esxVI_PerfMetricIntSeries_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfMetricIntSeries,
{
    /* PerfMetricSeries */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(PerfMetricId, id)

    /* PerfMetricIntSeries */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(Long, value)
})

/* esxVI_PerfMetricIntSeries_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfMetricIntSeries)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfMetricSeries
 *          extended by PerfMetricIntSeries
 */

/* esxVI_PerfMetricSeries_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfMetricSeries)

/* esxVI_PerfMetricSeries_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(PerfMetricSeries,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(PerfMetricIntSeries)
},
{
    esxVI_PerfMetricSeries_Free(&item->_next);

    esxVI_PerfMetricId_Free(&item->id);
})

/* esxVI_PerfMetricSeries_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfMetricSeries,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(id)
})

/* esxVI_PerfMetricSeries_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(PerfMetricSeries,
{
    /* PerfMetricSeries */
    ESX_VI__TEMPLATE__DYNAMIC_CAST__ACCEPT(PerfMetricIntSeries)
})

/* esxVI_PerfMetricSeries_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfMetricSeries)

/* esxVI_PerfMetricSeries_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(PerfMetricSeries,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(PerfMetricIntSeries)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(PerfMetricId, id)
})

/* esxVI_PerfMetricSeries_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfMetricSeries)

/* esxVI_PerfMetricSeries_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfMetricSeries,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(PerfMetricId, id)
})

/* esxVI_PerfMetricSeries_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfMetricSeries)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfQuerySpec
 */

/* esxVI_PerfQuerySpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfQuerySpec)

/* esxVI_PerfQuerySpec_Free */
ESX_VI__TEMPLATE__FREE(PerfQuerySpec,
{
    esxVI_PerfQuerySpec_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->entity);
    esxVI_DateTime_Free(&item->startTime);
    esxVI_DateTime_Free(&item->endTime);
    esxVI_Int_Free(&item->maxSample);
    esxVI_PerfMetricId_Free(&item->metricId);
    esxVI_Int_Free(&item->intervalId);
    VIR_FREE(item->format);
})

/* esxVI_PerfQuerySpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfQuerySpec,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(entity)
})

/* esxVI_PerfQuerySpec_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfQuerySpec)

/* esxVI_PerfQuerySpec_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PerfQuerySpec,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, entity)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(DateTime, startTime)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(DateTime, endTime)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, maxSample)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(PerfMetricId, metricId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, intervalId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, format)
})

/* esxVI_PerfQuerySpec_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfQuerySpec)

/* esxVI_PerfQuerySpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfQuerySpec,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, entity)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, startTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, endTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, maxSample)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(PerfMetricId, metricId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, intervalId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, format)
})

/* esxVI_PerfQuerySpec_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfQuerySpec)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PerfSampleInfo
 */

/* esxVI_PerfSampleInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(PerfSampleInfo)

/* esxVI_PerfSampleInfo_Free */
ESX_VI__TEMPLATE__FREE(PerfSampleInfo,
{
    esxVI_PerfSampleInfo_Free(&item->_next);

    esxVI_DateTime_Free(&item->timestamp);
    esxVI_Int_Free(&item->interval);
})

/* esxVI_PerfSampleInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(PerfSampleInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(timestamp)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(interval)
})

/* esxVI_PerfSampleInfo_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PerfSampleInfo)

/* esxVI_PerfSampleInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PerfSampleInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(DateTime, timestamp)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, interval)
})

/* esxVI_PerfSampleInfo_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PerfSampleInfo)

/* esxVI_PerfSampleInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PerfSampleInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, timestamp)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, interval)
})

/* esxVI_PerfSampleInfo_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PerfSampleInfo)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PropertyChange
 */

/* esxVI_PropertyChange_Alloc */
ESX_VI__TEMPLATE__ALLOC(PropertyChange)

/* esxVI_PropertyChange_Free */
ESX_VI__TEMPLATE__FREE(PropertyChange,
{
    esxVI_PropertyChange_Free(&item->_next);

    VIR_FREE(item->name);
    esxVI_AnyType_Free(&item->val);
})

/* esxVI_PropertyChange_Validate */
ESX_VI__TEMPLATE__VALIDATE(PropertyChange,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(op)
})

/* esxVI_PropertyChange_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PropertyChange)

/* esxVI_PropertyChange_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PropertyChange,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(PropertyChangeOp, op)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(AnyType, val)
})

/* esxVI_PropertyChange_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PropertyChange)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PropertyFilterSpec
 */

/* esxVI_PropertyFilterSpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(PropertyFilterSpec)

/* esxVI_PropertyFilterSpec_Free */
ESX_VI__TEMPLATE__FREE(PropertyFilterSpec,
{
    esxVI_PropertyFilterSpec_Free(&item->_next);

    esxVI_PropertySpec_Free(&item->propSet);
    esxVI_ObjectSpec_Free(&item->objectSet);
})

/* esxVI_PropertyFilterSpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(PropertyFilterSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(propSet)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(objectSet)
})

/* esxVI_PropertyFilterSpec_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PropertyFilterSpec)

/* esxVI_PropertyFilterSpec_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PropertyFilterSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(PropertySpec, propSet)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(ObjectSpec, objectSet)
})

/* esxVI_PropertyFilterSpec_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PropertyFilterSpec)

/* esxVI_PropertyFilterSpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PropertyFilterSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(PropertySpec, propSet)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(ObjectSpec, objectSet)
})

/* esxVI_PropertyFilterSpec_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PropertyFilterSpec)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PropertyFilterUpdate
 */

/* esxVI_PropertyFilterUpdate_Alloc */
ESX_VI__TEMPLATE__ALLOC(PropertyFilterUpdate)

/* esxVI_PropertyFilterUpdate_Free */
ESX_VI__TEMPLATE__FREE(PropertyFilterUpdate,
{
    esxVI_PropertyFilterUpdate_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->filter);
    esxVI_ObjectUpdate_Free(&item->objectSet);
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_PropertyFilterUpdate_Validate */
ESX_VI__TEMPLATE__VALIDATE(PropertyFilterUpdate,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(filter)
    /* FIXME: missingSet is currently ignored */
})

/* esxVI_PropertyFilterUpdate_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PropertyFilterUpdate)

/* esxVI_PropertyFilterUpdate_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PropertyFilterUpdate,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, filter)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(ObjectUpdate, objectSet)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(missingSet) /* FIXME */
})

/* esxVI_PropertyFilterUpdate_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PropertyFilterUpdate)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: PropertySpec
 */

/* esxVI_PropertySpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(PropertySpec)

/* esxVI_PropertySpec_Free */
ESX_VI__TEMPLATE__FREE(PropertySpec,
{
    esxVI_PropertySpec_Free(&item->_next);

    VIR_FREE(item->type);
    esxVI_String_Free(&item->pathSet);
})

/* esxVI_PropertySpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(PropertySpec,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(type)
})

/* esxVI_PropertySpec_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(PropertySpec)

/* esxVI_PropertySpec_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(PropertySpec,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, all)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(String, pathSet)
})

/* esxVI_PropertySpec_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(PropertySpec)

/* esxVI_PropertySpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(PropertySpec,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, all)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(String, pathSet)
})

/* esxVI_PropertySpec_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(PropertySpec)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ResourceAllocationInfo
 */

/* esxVI_ResourceAllocationInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(ResourceAllocationInfo)

/* esxVI_ResourceAllocationInfo_Free */
ESX_VI__TEMPLATE__FREE(ResourceAllocationInfo,
{
    esxVI_Long_Free(&item->reservation);
    esxVI_Long_Free(&item->limit);
    esxVI_SharesInfo_Free(&item->shares);
    esxVI_Long_Free(&item->overheadLimit);
})

/* esxVI_ResourceAllocationInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(ResourceAllocationInfo,
{
    /* no required properties */
})

/* esxVI_ResourceAllocationInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(ResourceAllocationInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, reservation)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, expandableReservation)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, limit)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(SharesInfo, shares)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, overheadLimit)
})

/* esxVI_ResourceAllocationInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ResourceAllocationInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, reservation)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, expandableReservation)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, limit)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(SharesInfo, shares)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, overheadLimit)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ResourcePoolResourceUsage
 */

/* esxVI_ResourcePoolResourceUsage_Alloc */
ESX_VI__TEMPLATE__ALLOC(ResourcePoolResourceUsage)

/* esxVI_ResourcePoolResourceUsage_Free */
ESX_VI__TEMPLATE__FREE(ResourcePoolResourceUsage,
{
    esxVI_Long_Free(&item->reservationUsed);
    esxVI_Long_Free(&item->reservationUsedForVm);
    esxVI_Long_Free(&item->unreservedForPool);
    esxVI_Long_Free(&item->unreservedForVm);
    esxVI_Long_Free(&item->overallUsage);
    esxVI_Long_Free(&item->maxUsage);
})

/* esxVI_ResourcePoolResourceUsage_Validate */
ESX_VI__TEMPLATE__VALIDATE(ResourcePoolResourceUsage,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(reservationUsed)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(reservationUsedForVm)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(unreservedForPool)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(unreservedForVm)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(overallUsage)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(maxUsage)
})

/* esxVI_ResourcePoolResourceUsage_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(ResourcePoolResourceUsage,
{
})

/* esxVI_ResourcePoolResourceUsage_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(ResourcePoolResourceUsage,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, reservationUsed)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, reservationUsedForVm)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, unreservedForPool)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, unreservedForVm)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, overallUsage)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, maxUsage)
})

/* esxVI_ResourcePoolResourceUsage_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ResourcePoolResourceUsage,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, reservationUsed)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, reservationUsedForVm)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, unreservedForPool)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, unreservedForVm)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, overallUsage)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, maxUsage)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: SelectionSpec
 *          extended by TraversalSpec
 */

/* esxVI_SelectionSpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(SelectionSpec)

/* esxVI_SelectionSpec_Free */
ESX_VI__TEMPLATE__DYNAMIC_FREE(SelectionSpec,
{
    ESX_VI__TEMPLATE__DISPATCH__FREE(TraversalSpec)
},
{
    esxVI_SelectionSpec_Free(&item->_next);

    VIR_FREE(item->name);
})

/* esxVI_SelectionSpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(SelectionSpec,
{
    /* no required properties */
})

/* esxVI_SelectionSpec_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(SelectionSpec,
{
    /* SelectionSpec */
    ESX_VI__TEMPLATE__DYNAMIC_CAST__ACCEPT(TraversalSpec)
})

/* esxVI_SelectionSpec_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(SelectionSpec)

/* esxVI_SelectionSpec_Serialize */
ESX_VI__TEMPLATE__DYNAMIC_SERIALIZE(SelectionSpec,
{
    ESX_VI__TEMPLATE__DISPATCH__SERIALIZE(TraversalSpec)
},
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
})

/* esxVI_SelectionSpec_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(SelectionSpec)

/* esxVI_SelectionSpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(SelectionSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
})

/* esxVI_SelectionSpec_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(SelectionSpec)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: ServiceContent
 */

/* esxVI_ServiceContent_Alloc */
ESX_VI__TEMPLATE__ALLOC(ServiceContent)

/* esxVI_ServiceContent_Free */
ESX_VI__TEMPLATE__FREE(ServiceContent,
{
    esxVI_ManagedObjectReference_Free(&item->rootFolder);
    esxVI_ManagedObjectReference_Free(&item->propertyCollector);
    esxVI_ManagedObjectReference_Free(&item->viewManager);
    esxVI_AboutInfo_Free(&item->about);
    esxVI_ManagedObjectReference_Free(&item->setting);
    esxVI_ManagedObjectReference_Free(&item->userDirectory);
    esxVI_ManagedObjectReference_Free(&item->sessionManager);
    esxVI_ManagedObjectReference_Free(&item->authorizationManager);
    esxVI_ManagedObjectReference_Free(&item->perfManager);
    esxVI_ManagedObjectReference_Free(&item->scheduledTaskManager);
    esxVI_ManagedObjectReference_Free(&item->alarmManager);
    esxVI_ManagedObjectReference_Free(&item->eventManager);
    esxVI_ManagedObjectReference_Free(&item->taskManager);
    esxVI_ManagedObjectReference_Free(&item->extensionManager);
    esxVI_ManagedObjectReference_Free(&item->customizationSpecManager);
    esxVI_ManagedObjectReference_Free(&item->customFieldsManager);
    esxVI_ManagedObjectReference_Free(&item->accountManager);
    esxVI_ManagedObjectReference_Free(&item->diagnosticManager);
    esxVI_ManagedObjectReference_Free(&item->licenseManager);
    esxVI_ManagedObjectReference_Free(&item->searchIndex);
    esxVI_ManagedObjectReference_Free(&item->fileManager);
    esxVI_ManagedObjectReference_Free(&item->virtualDiskManager);
    esxVI_ManagedObjectReference_Free(&item->virtualizationManager);
})

/* esxVI_ServiceContent_Validate */
ESX_VI__TEMPLATE__VALIDATE(ServiceContent,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(rootFolder)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(propertyCollector)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(about)
})

/* esxVI_ServiceContent_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(ServiceContent,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, rootFolder)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, propertyCollector)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, viewManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(AboutInfo, about)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, setting)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, userDirectory)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, sessionManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, authorizationManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, perfManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, scheduledTaskManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, alarmManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, eventManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, taskManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, extensionManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, customizationSpecManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, customFieldsManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, accountManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, diagnosticManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, licenseManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, searchIndex)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, fileManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, virtualDiskManager)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ManagedObjectReference, virtualizationManager)
})

/* esxVI_ServiceContent_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(ServiceContent,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, rootFolder)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, propertyCollector)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, viewManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(AboutInfo, about)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, setting)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, userDirectory)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, sessionManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, authorizationManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, perfManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, scheduledTaskManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, alarmManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, eventManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, taskManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, extensionManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, customizationSpecManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, customFieldsManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, accountManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, diagnosticManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, licenseManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, searchIndex)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, fileManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, virtualDiskManager)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, virtualizationManager)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: SharesInfo
 */

/* esxVI_SharesInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(SharesInfo)

/* esxVI_SharesInfo_Free */
ESX_VI__TEMPLATE__FREE(SharesInfo,
{
    esxVI_Int_Free(&item->shares);
})

/* esxVI_SharesInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(SharesInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(shares)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(level)
})

/* esxVI_SharesInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(SharesInfo,
{
})

/* esxVI_SharesInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(SharesInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, shares)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(SharesLevel, level)
})

/* esxVI_SharesInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(SharesInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, shares)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(SharesLevel, level)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: TaskInfo
 */

/* esxVI_TaskInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(TaskInfo)

/* esxVI_TaskInfo_Free */
ESX_VI__TEMPLATE__FREE(TaskInfo,
{
    esxVI_TaskInfo_Free(&item->_next);

    VIR_FREE(item->key);
    esxVI_ManagedObjectReference_Free(&item->task);
    VIR_FREE(item->name);
    VIR_FREE(item->descriptionId);
    esxVI_ManagedObjectReference_Free(&item->entity);
    VIR_FREE(item->entityName);
    esxVI_ManagedObjectReference_Free(&item->locked);
    /* FIXME: error is currently ignored */
    esxVI_AnyType_Free(&item->result);
    esxVI_Int_Free(&item->progress);
    /* FIXME: reason is currently ignored */
    esxVI_DateTime_Free(&item->queueTime);
    esxVI_DateTime_Free(&item->startTime);
    esxVI_DateTime_Free(&item->completeTime);
    esxVI_Int_Free(&item->eventChainId);
})

/* esxVI_TaskInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(TaskInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(key)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(task)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(descriptionId)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(state)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(cancelled)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(cancelable)
    /* FIXME: error is currently ignored */
    /* FIXME: reason is currently ignored */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(queueTime)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(eventChainId)
})

/* esxVI_TaskInfo_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(TaskInfo)

/* esxVI_TaskInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(TaskInfo,
{
})

/* esxVI_TaskInfo_CastListFromAnyType */
ESX_VI__TEMPLATE__LIST__CAST_FROM_ANY_TYPE(TaskInfo)

/* esxVI_TaskInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(TaskInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, key)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, task)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, descriptionId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, entity)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, entityName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(ManagedObjectReference, locked)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(TaskInfoState, state)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, cancelled)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, cancelable)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(error) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(AnyType, result)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, progress)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(reason) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, queueTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, startTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, completeTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, eventChainId)
})

/* esxVI_TaskInfo_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(TaskInfo)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: TraversalSpec
 *          extends SelectionSpec
 */

/* esxVI_TraversalSpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(TraversalSpec)

/* esxVI_TraversalSpec_Free */
ESX_VI__TEMPLATE__FREE(TraversalSpec,
{
    esxVI_TraversalSpec_Free(&item->_next);

    /* SelectionSpec */
    VIR_FREE(item->name);

    /* TraversalSpec */
    VIR_FREE(item->type);
    VIR_FREE(item->path);
    esxVI_SelectionSpec_Free(&item->selectSet);
})

/* esxVI_TraversalSpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(TraversalSpec,
{
    /* SelectionSpec */
    /* no required properties */

    /* TraversalSpec */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(type)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(path)
})

/* esxVI_TraversalSpec_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(TraversalSpec,
{
})

/* esxVI_TraversalSpec_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(TraversalSpec)

/* esxVI_TraversalSpec_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(TraversalSpec,
{
    /* SelectionSpec */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)

    /* TraversalSpec */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, path)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Boolean, skip)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(SelectionSpec, selectSet)
})

/* esxVI_TraversalSpec_SerializeList */
ESX_VI__TEMPLATE__LIST__SERIALIZE(TraversalSpec)

/* esxVI_TraversalSpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(TraversalSpec,
{
    /* SelectionSpec */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)

    /* TraversalSpec */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, type)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, path)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, skip)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(SelectionSpec, selectSet)
})

/* esxVI_TraversalSpec_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(TraversalSpec)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: UpdateSet
 */

/* esxVI_UpdateSet_Alloc */
ESX_VI__TEMPLATE__ALLOC(UpdateSet)

/* esxVI_UpdateSet_Free */
ESX_VI__TEMPLATE__FREE(UpdateSet,
{
    VIR_FREE(item->version);
    esxVI_PropertyFilterUpdate_Free(&item->filterSet);
})

/* esxVI_UpdateSet_Validate */
ESX_VI__TEMPLATE__VALIDATE(UpdateSet,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(version)
})

/* esxVI_UpdateSet_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(UpdateSet,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(PropertyFilterUpdate, filterSet)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: UserSession
 */

/* esxVI_UserSession_Alloc */
ESX_VI__TEMPLATE__ALLOC(UserSession)

/* esxVI_UserSession_Free */
ESX_VI__TEMPLATE__FREE(UserSession,
{
    VIR_FREE(item->key);
    VIR_FREE(item->userName);
    VIR_FREE(item->fullName);
    esxVI_DateTime_Free(&item->loginTime);
    esxVI_DateTime_Free(&item->lastActiveTime);
    VIR_FREE(item->locale);
    VIR_FREE(item->messageLocale);
})

/* esxVI_UserSession_Validate */
ESX_VI__TEMPLATE__VALIDATE(UserSession,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(key)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(userName)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(fullName)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(loginTime)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(lastActiveTime)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(locale)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(messageLocale)
})

/* esxVI_UserSession_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(UserSession,
{
})

/* esxVI_UserSession_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(UserSession,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, key)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, userName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, fullName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(DateTime, loginTime)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(DateTime, lastActiveTime)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, locale)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, messageLocale)
})

/* esxVI_UserSession_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(UserSession,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, key)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, userName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, fullName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, loginTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, lastActiveTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, locale)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, messageLocale)
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: VirtualMachineConfigSpec
 */

/* esxVI_VirtualMachineConfigSpec_Alloc */
ESX_VI__TEMPLATE__ALLOC(VirtualMachineConfigSpec)

/* esxVI_VirtualMachineConfigSpec_Free */
ESX_VI__TEMPLATE__FREE(VirtualMachineConfigSpec,
{
    VIR_FREE(item->changeVersion);
    VIR_FREE(item->name);
    VIR_FREE(item->version);
    VIR_FREE(item->uuid);
    esxVI_Long_Free(&item->npivNodeWorldWideName);
    esxVI_Long_Free(&item->npivPortWorldWideName);
    VIR_FREE(item->npivWorldWideNameType);
    VIR_FREE(item->npivWorldWideNameOp);
    VIR_FREE(item->locationId);
    VIR_FREE(item->guestId);
    VIR_FREE(item->alternateGuestName);
    VIR_FREE(item->annotation);
    /* FIXME: files is currently ignored */
    /* FIXME: tools is currently ignored */
    /* FIXME: flags is currently ignored */
    /* FIXME: consolePreferences is currently ignored */
    /* FIXME: powerOpInfo is currently ignored */
    esxVI_Int_Free(&item->numCPUs);
    esxVI_Long_Free(&item->memoryMB);
    /* FIXME: deviceChange is currently ignored */
    esxVI_ResourceAllocationInfo_Free(&item->cpuAllocation);
    esxVI_ResourceAllocationInfo_Free(&item->memoryAllocation);
    /* FIXME: cpuAffinity is currently ignored */
    /* FIXME: memoryAffinity is currently ignored */
    /* FIXME: networkShaper is currently ignored */
    /* FIXME: cpuFeatureMask is currently ignored */
    /* FIXME: extraConfig is currently ignored */
    VIR_FREE(item->swapPlacement);
    /* FIXME: bootOptions is currently ignored */
})

/* esxVI_VirtualMachineConfigSpec_Validate */
ESX_VI__TEMPLATE__VALIDATE(VirtualMachineConfigSpec,
{
    /* FIXME: files is currently ignored */
    /* FIXME: tools is currently ignored */
    /* FIXME: flags is currently ignored */
    /* FIXME: consolePreferences is currently ignored */
    /* FIXME: powerOpInfo is currently ignored */
    /* FIXME: deviceChange is currently ignored */
    /* FIXME: cpuAffinity is currently ignored */
    /* FIXME: memoryAffinity is currently ignored */
    /* FIXME: networkShaper is currently ignored */
    /* FIXME: cpuFeatureMask is currently ignored */
    /* FIXME: extraConfig is currently ignored */
    /* FIXME: bootOptions is currently ignored */
})

/* esxVI_VirtualMachineConfigSpec_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(VirtualMachineConfigSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, changeVersion)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, uuid)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(Long, npivNodeWorldWideName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_LIST(Long, npivPortWorldWideName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, npivWorldWideNameType)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, npivWorldWideNameOp)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, locationId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, guestId)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, alternateGuestName)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, annotation)
    /* FIXME: files is currently ignored */
    /* FIXME: tools is currently ignored */
    /* FIXME: flags is currently ignored */
    /* FIXME: consolePreferences is currently ignored */
    /* FIXME: powerOpInfo is currently ignored */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Int, numCPUs)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, memoryMB)
    /* FIXME: deviceChange is currently ignored */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ResourceAllocationInfo, cpuAllocation)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ResourceAllocationInfo, memoryAllocation)
    /* FIXME: cpuAffinity is currently ignored */
    /* FIXME: memoryAffinity is currently ignored */
    /* FIXME: networkShaper is currently ignored */
    /* FIXME: cpuFeatureMask is currently ignored */
    /* FIXME: extraConfig is currently ignored */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, swapPlacement)
    /* FIXME: bootOptions is currently ignored */
})

/* esxVI_VirtualMachineConfigSpec_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(VirtualMachineConfigSpec,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, changeVersion)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, version)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, uuid)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(Long, npivNodeWorldWideName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(Long, npivPortWorldWideName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, npivWorldWideNameType)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, npivWorldWideNameOp)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, locationId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, guestId)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, alternateGuestName)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, annotation)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(files) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(tools) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(flags) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(consolePreferences) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(powerOpInfo) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Int, numCPUs)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, memoryMB)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(deviceChange) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ResourceAllocationInfo, cpuAllocation)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ResourceAllocationInfo, memoryAllocation)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(cpuAffinity) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(memoryAffinity) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(networkShaper) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(cpuFeatureMask) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(extraConfig) /* FIXME */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, swapPlacement)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(bootOptions) /* FIXME */
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: VirtualMachineQuestionInfo
 */

/* esxVI_VirtualMachineQuestionInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(VirtualMachineQuestionInfo)

/* esxVI_VirtualMachineQuestionInfo_Free */
ESX_VI__TEMPLATE__FREE(VirtualMachineQuestionInfo,
{
    VIR_FREE(item->id);
    VIR_FREE(item->text);
    esxVI_ChoiceOption_Free(&item->choice);
    /* FIXME: message is currently ignored */
})

/* esxVI_VirtualMachineQuestionInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(VirtualMachineQuestionInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(id)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(text)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(choice)
    /* FIXME: message is currently ignored */
})

/* esxVI_VirtualMachineQuestionInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(VirtualMachineQuestionInfo,
{
})

/* esxVI_VirtualMachineQuestionInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(VirtualMachineQuestionInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, id)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, text)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(ChoiceOption, choice)
    /* FIXME: message is currently ignored */
})

/* esxVI_VirtualMachineQuestionInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(VirtualMachineQuestionInfo,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, id)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, text)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ChoiceOption, choice)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_IGNORE(message) /* FIXME */
})



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: VirtualMachineSnapshotTree
 */

/* esxVI_VirtualMachineSnapshotTree_Alloc */
ESX_VI__TEMPLATE__ALLOC(VirtualMachineSnapshotTree)

/* esxVI_VirtualMachineSnapshotTree_Free */
ESX_VI__TEMPLATE__FREE(VirtualMachineSnapshotTree,
{
    esxVI_VirtualMachineSnapshotTree_Free(&item->_next);

    esxVI_ManagedObjectReference_Free(&item->snapshot);
    esxVI_ManagedObjectReference_Free(&item->vm);
    VIR_FREE(item->name);
    VIR_FREE(item->description);
    esxVI_DateTime_Free(&item->createTime);
    esxVI_VirtualMachineSnapshotTree_Free(&item->childSnapshotList);
})

/* esxVI_VirtualMachineSnapshotTree_Validate */
ESX_VI__TEMPLATE__VALIDATE(VirtualMachineSnapshotTree,
{
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(snapshot)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(vm)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(description)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(createTime)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(state)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(quiesced)
})

/* esxVI_VirtualMachineSnapshotTree_AppendToList */
ESX_VI__TEMPLATE__LIST__APPEND(VirtualMachineSnapshotTree)

/* esxVI_VirtualMachineSnapshotTree_DeepCopy */
ESX_VI__TEMPLATE__DEEP_COPY(VirtualMachineSnapshotTree,
{
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY(ManagedObjectReference, snapshot)
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY(ManagedObjectReference, vm)
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY_VALUE(String, description)
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY(DateTime, createTime)
    (*dest)->state = src->state;
    (*dest)->quiesced = src->quiesced;
    ESX_VI__TEMPLATE__PROPERTY__DEEP_COPY_LIST(VirtualMachineSnapshotTree, childSnapshotList)
})

/* esxVI_VirtualMachineSnapshotTree_DeepCopyList */
ESX_VI__TEMPLATE__LIST__DEEP_COPY(VirtualMachineSnapshotTree)

/* esxVI_VirtualMachineSnapshotTree_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(VirtualMachineSnapshotTree,
{
})

/* esxVI_VirtualMachineSnapshotTree_CastListFromAnyType */
ESX_VI__TEMPLATE__LIST__CAST_FROM_ANY_TYPE(VirtualMachineSnapshotTree)

/* esxVI_VirtualMachineSnapshotTree_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(VirtualMachineSnapshotTree,
{
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, snapshot)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(ManagedObjectReference, vm)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, description)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(DateTime, createTime)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(VirtualMachinePowerState, state)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Boolean, quiesced)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_LIST(VirtualMachineSnapshotTree, childSnapshotList)
})

/* esxVI_VirtualMachineSnapshotTree_DeserializeList */
ESX_VI__TEMPLATE__LIST__DESERIALIZE(VirtualMachineSnapshotTree)



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * VI Type: VmfsDatastoreInfo
 *          extends DatastoreInfo
 */

/* esxVI_VmfsDatastoreInfo_Alloc */
ESX_VI__TEMPLATE__ALLOC(VmfsDatastoreInfo)

/* esxVI_VmfsDatastoreInfo_Free */
ESX_VI__TEMPLATE__FREE(VmfsDatastoreInfo,
{
    /* DatastoreInfo */
    VIR_FREE(item->name);
    VIR_FREE(item->url);
    esxVI_Long_Free(&item->freeSpace);
    esxVI_Long_Free(&item->maxFileSize);

    /* VmfsDatastoreInfo */
    esxVI_HostVmfsVolume_Free(&item->vmfs);
})

/* esxVI_VmfsDatastoreInfo_Validate */
ESX_VI__TEMPLATE__VALIDATE(VmfsDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(name)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(url)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__REQUIRE(maxFileSize)

    /* VmfsDatastoreInfo */
    /* no required properties */
})

/* esxVI_VmfsDatastoreInfo_DynamicCast */
ESX_VI__TEMPLATE__DYNAMIC_CAST(VmfsDatastoreInfo,
{
})

/* esxVI_VmfsDatastoreInfo_CastFromAnyType */
ESX_VI__TEMPLATE__CAST_FROM_ANY_TYPE(VmfsDatastoreInfo,
{
})

/* esxVI_VmfsDatastoreInfo_Serialize */
ESX_VI__TEMPLATE__SERIALIZE(VmfsDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(Long, maxFileSize)

    /* VmfsDatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__SERIALIZE(HostVmfsVolume, vmfs)
})

/* esxVI_VmfsDatastoreInfo_Deserialize */
ESX_VI__TEMPLATE__DESERIALIZE(VmfsDatastoreInfo,
{
    /* DatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, name)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE_VALUE(String, url)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, freeSpace)
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(Long, maxFileSize)

    /* VmfsDatastoreInfo */
    ESX_VI__TEMPLATE__PROPERTY__DESERIALIZE(HostVmfsVolume, vmfs)
})



