/* Generated by esx_vi_generator.py */



/* esxVI_AnswerVM */
ESX_VI__METHOD(AnswerVM, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                const char *questionId,                    /* required */
                const char *answerChoice),                 /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(questionId)
    ESX_VI__METHOD__PARAMETER__REQUIRE(answerChoice)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, questionId)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, answerChoice)
})



/* esxVI_CancelTask */
ESX_VI__METHOD(CancelTask, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this),      /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_CreateFilter */
ESX_VI__METHOD(CreateFilter, propertyCollector,
               (esxVI_Context *ctx,
                esxVI_PropertyFilterSpec *spec,            /* required */
                esxVI_Boolean partialUpdates,              /* required */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(spec)
    ESX_VI__METHOD__PARAMETER__REQUIRE(partialUpdates)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(PropertyFilterSpec, spec)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, partialUpdates)
})



/* esxVI_CreateSnapshot_Task */
ESX_VI__METHOD(CreateSnapshot_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                const char *name,                          /* required */
                const char *description,                   /* optional */
                esxVI_Boolean memory,                      /* required */
                esxVI_Boolean quiesce,                     /* required */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(name)
    ESX_VI__METHOD__PARAMETER__REQUIRE(memory)
    ESX_VI__METHOD__PARAMETER__REQUIRE(quiesce)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, name)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, description)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, memory)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, quiesce)
})



/* esxVI_DestroyPropertyFilter */
ESX_VI__METHOD(DestroyPropertyFilter, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this),      /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_FindByIp */
ESX_VI__METHOD(FindByIp, searchIndex,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *datacenter,  /* optional */
                const char *ip,                            /* required */
                esxVI_Boolean vmSearch,                    /* required */
                esxVI_ManagedObjectReference **output),    /* optional */
               ManagedObjectReference, OptionalItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(ip)
    ESX_VI__METHOD__PARAMETER__REQUIRE(vmSearch)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, datacenter)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, ip)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, vmSearch)
})



/* esxVI_FindByUuid */
ESX_VI__METHOD(FindByUuid, searchIndex,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *datacenter,  /* optional */
                const char *uuid,                          /* required */
                esxVI_Boolean vmSearch,                    /* required */
                esxVI_ManagedObjectReference **output),    /* optional */
               ManagedObjectReference, OptionalItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(uuid)
    ESX_VI__METHOD__PARAMETER__REQUIRE(vmSearch)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, datacenter)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, uuid)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, vmSearch)
})



/* esxVI_Login */
ESX_VI__METHOD(Login, sessionManager,
               (esxVI_Context *ctx,
                const char *userName,                      /* required */
                const char *password,                      /* required */
                const char *locale,                        /* optional */
                esxVI_UserSession **output),               /* required */
               UserSession, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(userName)
    ESX_VI__METHOD__PARAMETER__REQUIRE(password)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, userName)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, password)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, locale)
})



/* esxVI_Logout */
ESX_VI__METHOD(Logout, sessionManager,
               (esxVI_Context *ctx),
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_MigrateVM_Task */
ESX_VI__METHOD(MigrateVM_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_ManagedObjectReference *pool,        /* optional */
                esxVI_ManagedObjectReference *host,        /* optional */
                esxVI_VirtualMachineMovePriority priority, /* required */
                esxVI_VirtualMachinePowerState state,      /* optional */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(priority)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, pool)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, host)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(VirtualMachineMovePriority, priority)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(VirtualMachinePowerState, state)
})



/* esxVI_PowerOffVM_Task */
ESX_VI__METHOD(PowerOffVM_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_PowerOnVM_Task */
ESX_VI__METHOD(PowerOnVM_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_ManagedObjectReference *host,        /* optional */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, host)
})



/* esxVI_QueryAvailablePerfMetric */
ESX_VI__METHOD(QueryAvailablePerfMetric, perfManager,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *entity,      /* required */
                esxVI_DateTime *beginTime,                 /* optional */
                esxVI_DateTime *endTime,                   /* optional */
                esxVI_Int *intervalId,                     /* optional */
                esxVI_PerfMetricId **output),              /* optional, list */
               PerfMetricId, OptionalList,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(entity)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, entity)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(DateTime, beginTime)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(DateTime, endTime)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Int, intervalId)
})



/* esxVI_QueryPerf */
ESX_VI__METHOD(QueryPerf, perfManager,
               (esxVI_Context *ctx,
                esxVI_PerfQuerySpec *querySpec,            /* required, list */
                esxVI_PerfEntityMetricBase **output),      /* optional, list */
               PerfEntityMetricBase, OptionalList,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(querySpec)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_LIST(PerfQuerySpec, querySpec)
})



/* esxVI_QueryPerfCounter */
ESX_VI__METHOD(QueryPerfCounter, perfManager,
               (esxVI_Context *ctx,
                esxVI_Int *counterId,                      /* required, list */
                esxVI_PerfCounterInfo **output),           /* optional, list */
               PerfCounterInfo, OptionalList,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(counterId)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_LIST(Int, counterId)
})



/* esxVI_RebootGuest */
ESX_VI__METHOD(RebootGuest, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this),      /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_ReconfigVM_Task */
ESX_VI__METHOD(ReconfigVM_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_VirtualMachineConfigSpec *spec,      /* required */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(spec)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(VirtualMachineConfigSpec, spec)
})



/* esxVI_RefreshDatastore */
ESX_VI__METHOD(RefreshDatastore, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this),      /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_RegisterVM_Task */
ESX_VI__METHOD(RegisterVM_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                const char *path,                          /* required */
                const char *name,                          /* optional */
                esxVI_Boolean asTemplate,                  /* required */
                esxVI_ManagedObjectReference *pool,        /* optional */
                esxVI_ManagedObjectReference *host,        /* optional */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(path)
    ESX_VI__METHOD__PARAMETER__REQUIRE(asTemplate)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, path)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, name)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, asTemplate)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, pool)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, host)
})



/* esxVI_RemoveSnapshot_Task */
ESX_VI__METHOD(RemoveSnapshot_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_Boolean removeChildren,              /* required */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(removeChildren)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(Boolean, removeChildren)
})



/* esxVI_RetrieveProperties */
ESX_VI__METHOD(RetrieveProperties, propertyCollector,
               (esxVI_Context *ctx,
                esxVI_PropertyFilterSpec *specSet,         /* required, list */
                esxVI_ObjectContent **output),             /* optional, list */
               ObjectContent, OptionalList,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(specSet)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_LIST(PropertyFilterSpec, specSet)
})



/* esxVI_RevertToSnapshot_Task */
ESX_VI__METHOD(RevertToSnapshot_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_ManagedObjectReference *host,        /* optional */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, host)
})



/* esxVI_SessionIsActive */
ESX_VI__METHOD(SessionIsActive, sessionManager,
               (esxVI_Context *ctx,
                const char *sessionID,                     /* required */
                const char *userName,                      /* required */
                esxVI_Boolean *output),                    /* required */
               Boolean, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
    ESX_VI__METHOD__PARAMETER__REQUIRE(sessionID)
    ESX_VI__METHOD__PARAMETER__REQUIRE(userName)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, sessionID)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, userName)
})



/* esxVI_ShutdownGuest */
ESX_VI__METHOD(ShutdownGuest, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this),      /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_SuspendVM_Task */
ESX_VI__METHOD(SuspendVM_Task, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this,       /* required */
                esxVI_ManagedObjectReference **output),    /* required */
               ManagedObjectReference, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_UnregisterVM */
ESX_VI__METHOD(UnregisterVM, /* explicit _this */,
               (esxVI_Context *ctx,
                esxVI_ManagedObjectReference *_this),      /* required */
               void, None,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
})



/* esxVI_WaitForUpdates */
ESX_VI__METHOD(WaitForUpdates, propertyCollector,
               (esxVI_Context *ctx,
                const char *version,                       /* optional */
                esxVI_UpdateSet **output),                 /* required */
               UpdateSet, RequiredItem,
{
    ESX_VI__METHOD__PARAMETER__REQUIRE(_this)
},
{
    ESX_VI__METHOD__PARAMETER__SERIALIZE(ManagedObjectReference, _this)
    ESX_VI__METHOD__PARAMETER__SERIALIZE_VALUE(String, version)
})



