#!/bin/sh

set -e
set -x

export LIBVIRT_DEFAULT_URI='lxc:///'

XML=debian/tests/smoke-lxc.xml
DOMAIN=sl

cleanup()
{
   if [ -z "$CLEANED_UP" ]; then
     virsh destroy ${DOMAIN}  || true
     virsh undefine ${DOMAIN} || true
     CLEANED_UP=1
   fi
}

trap cleanup EXIT

virt-host-validate lxc
virsh capabilities
virsh capabilities | grep -qs 'emulator>/usr/lib/libvirt/libvirt_lxc'
virsh capabilities | grep -qs 'os_type>exe'
virt-xml-validate ${XML}
virsh define ${XML}
virsh start ${DOMAIN}
virsh list | grep -qs "${DOMAIN}[[:space:]]\+running"
virsh lxc-enter-namespace --noseclabel ${DOMAIN} /bin/ls /bin/ls
virsh destroy ${DOMAIN}
virsh undefine ${DOMAIN}
CLEANED_UP=1

echo 'Smoke test of lxc:/// succesful'
exit 0
