/* Automatically generated by remote_generator.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */
static int qemuDispatchMonitorCommand(
    virNetServerPtr server,
    virNetServerClientPtr client,
    virNetMessageHeaderPtr hdr,
    virNetMessageErrorPtr rerr,
    qemu_monitor_command_args *args,
    qemu_monitor_command_ret *ret);
static int qemuDispatchMonitorCommandHelper(
    virNetServerPtr server,
    virNetServerClientPtr client,
    virNetMessageHeaderPtr hdr,
    virNetMessageErrorPtr rerr,
    void *args,
    void *ret)
{
  VIR_DEBUG("server=%p client=%p hdr=%p rerr=%p args=%p ret=%p", server, client, hdr, rerr, args, ret);
  return qemuDispatchMonitorCommand(server, client, hdr, rerr, args, ret);
}
/* qemuDispatchMonitorCommand body has to be implemented manually */



virNetServerProgramProc qemuProcs[] = {
{ /* Unused 0 */
   NULL,
   0,
   (xdrproc_t)xdr_void,
   0,
   (xdrproc_t)xdr_void,
   true 
},
{ /* Method MonitorCommand => 1 */
   qemuDispatchMonitorCommandHelper,
   sizeof(qemu_monitor_command_args),
   (xdrproc_t)xdr_qemu_monitor_command_args,
   sizeof(qemu_monitor_command_ret),
   (xdrproc_t)xdr_qemu_monitor_command_ret,
   true 
},
};
size_t qemuNProcs = ARRAY_CARDINALITY(qemuProcs);
