/* Automatically generated by gendispatch.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */
virNetServerProgramProc virLXCProtocolProcs[] = {
};
size_t virLXCProtocolNProcs = ARRAY_CARDINALITY(virLXCProtocolProcs);
