/* Automatically generated from ./admin/admin_protocol.x by gendispatch.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */

static int
remoteAdminDaemonGetVersion(virAdmDaemonPtr conn, unsigned long long *libVer)
{
    int rv = -1;
    remoteAdminPrivPtr priv = conn->privateData;
    admin_daemon_get_version_ret ret;

    virObjectLock(priv);

    memset(&ret, 0, sizeof(ret));

    if (call(conn, 0, ADMIN_PROC_DAEMON_GET_VERSION,
             (xdrproc_t)xdr_void, (char *)NULL,
             (xdrproc_t)xdr_admin_daemon_get_version_ret, (char *)&ret) == -1) {
        goto done;
    }

    *libVer = ret.libVer;
    rv = 0;

done:
    virObjectUnlock(priv);
    return rv;
}
