/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADMIN_PROTOCOL_H_RPCGEN
#define _ADMIN_PROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADMIN_STRING_MAX 4194304

typedef char *admin_nonnull_string;

typedef admin_nonnull_string *admin_string;

struct admin_connect_open_args {
        u_int flags;
};
typedef struct admin_connect_open_args admin_connect_open_args;
#define ADMIN_PROGRAM 0x06900690
#define ADMIN_PROTOCOL_VERSION 1

enum admin_procedure {
        ADMIN_PROC_CONNECT_OPEN = 1,
        ADMIN_PROC_CONNECT_CLOSE = 2,
};
typedef enum admin_procedure admin_procedure;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_admin_nonnull_string (XDR *, admin_nonnull_string*);
extern  bool_t xdr_admin_string (XDR *, admin_string*);
extern  bool_t xdr_admin_connect_open_args (XDR *, admin_connect_open_args*);
extern  bool_t xdr_admin_procedure (XDR *, admin_procedure*);

#else /* K&R C */
extern bool_t xdr_admin_nonnull_string ();
extern bool_t xdr_admin_string ();
extern bool_t xdr_admin_connect_open_args ();
extern bool_t xdr_admin_procedure ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADMIN_PROTOCOL_H_RPCGEN */
