/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* LIBVIRT_EVENT_POLL_ADD_HANDLE ( int watch, int fd, int events, void *cb, void *opaque, void *ff) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_ADD_HANDLE_ENABLED() __builtin_expect (event_poll_add_handle_semaphore, 0)
#define libvirt_event_poll_add_handle_semaphore event_poll_add_handle_semaphore
#else
#define LIBVIRT_EVENT_POLL_ADD_HANDLE_ENABLED() __builtin_expect (libvirt_event_poll_add_handle_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_add_handle_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_ADD_HANDLE(arg1,arg2,arg3,arg4,arg5,arg6) \
STAP_PROBE6(libvirt,event_poll_add_handle,arg1,arg2,arg3,arg4,arg5,arg6)

/* LIBVIRT_EVENT_POLL_UPDATE_HANDLE ( int watch, int events) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_UPDATE_HANDLE_ENABLED() __builtin_expect (event_poll_update_handle_semaphore, 0)
#define libvirt_event_poll_update_handle_semaphore event_poll_update_handle_semaphore
#else
#define LIBVIRT_EVENT_POLL_UPDATE_HANDLE_ENABLED() __builtin_expect (libvirt_event_poll_update_handle_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_update_handle_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_UPDATE_HANDLE(arg1,arg2) \
STAP_PROBE2(libvirt,event_poll_update_handle,arg1,arg2)

/* LIBVIRT_EVENT_POLL_REMOVE_HANDLE ( int watch) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_REMOVE_HANDLE_ENABLED() __builtin_expect (event_poll_remove_handle_semaphore, 0)
#define libvirt_event_poll_remove_handle_semaphore event_poll_remove_handle_semaphore
#else
#define LIBVIRT_EVENT_POLL_REMOVE_HANDLE_ENABLED() __builtin_expect (libvirt_event_poll_remove_handle_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_remove_handle_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_REMOVE_HANDLE(arg1) \
STAP_PROBE1(libvirt,event_poll_remove_handle,arg1)

/* LIBVIRT_EVENT_POLL_DISPATCH_HANDLE ( int watch, int events) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_DISPATCH_HANDLE_ENABLED() __builtin_expect (event_poll_dispatch_handle_semaphore, 0)
#define libvirt_event_poll_dispatch_handle_semaphore event_poll_dispatch_handle_semaphore
#else
#define LIBVIRT_EVENT_POLL_DISPATCH_HANDLE_ENABLED() __builtin_expect (libvirt_event_poll_dispatch_handle_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_dispatch_handle_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_DISPATCH_HANDLE(arg1,arg2) \
STAP_PROBE2(libvirt,event_poll_dispatch_handle,arg1,arg2)

/* LIBVIRT_EVENT_POLL_PURGE_HANDLE ( int watch) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_PURGE_HANDLE_ENABLED() __builtin_expect (event_poll_purge_handle_semaphore, 0)
#define libvirt_event_poll_purge_handle_semaphore event_poll_purge_handle_semaphore
#else
#define LIBVIRT_EVENT_POLL_PURGE_HANDLE_ENABLED() __builtin_expect (libvirt_event_poll_purge_handle_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_purge_handle_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_PURGE_HANDLE(arg1) \
STAP_PROBE1(libvirt,event_poll_purge_handle,arg1)

/* LIBVIRT_EVENT_POLL_ADD_TIMEOUT ( int timer, int frequency, void *cb, void *opaque, void *ff) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_ADD_TIMEOUT_ENABLED() __builtin_expect (event_poll_add_timeout_semaphore, 0)
#define libvirt_event_poll_add_timeout_semaphore event_poll_add_timeout_semaphore
#else
#define LIBVIRT_EVENT_POLL_ADD_TIMEOUT_ENABLED() __builtin_expect (libvirt_event_poll_add_timeout_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_add_timeout_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_ADD_TIMEOUT(arg1,arg2,arg3,arg4,arg5) \
STAP_PROBE5(libvirt,event_poll_add_timeout,arg1,arg2,arg3,arg4,arg5)

/* LIBVIRT_EVENT_POLL_UPDATE_TIMEOUT ( int timer, int frequency) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_UPDATE_TIMEOUT_ENABLED() __builtin_expect (event_poll_update_timeout_semaphore, 0)
#define libvirt_event_poll_update_timeout_semaphore event_poll_update_timeout_semaphore
#else
#define LIBVIRT_EVENT_POLL_UPDATE_TIMEOUT_ENABLED() __builtin_expect (libvirt_event_poll_update_timeout_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_update_timeout_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_UPDATE_TIMEOUT(arg1,arg2) \
STAP_PROBE2(libvirt,event_poll_update_timeout,arg1,arg2)

/* LIBVIRT_EVENT_POLL_REMOVE_TIMEOUT ( int timer) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_REMOVE_TIMEOUT_ENABLED() __builtin_expect (event_poll_remove_timeout_semaphore, 0)
#define libvirt_event_poll_remove_timeout_semaphore event_poll_remove_timeout_semaphore
#else
#define LIBVIRT_EVENT_POLL_REMOVE_TIMEOUT_ENABLED() __builtin_expect (libvirt_event_poll_remove_timeout_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_remove_timeout_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_REMOVE_TIMEOUT(arg1) \
STAP_PROBE1(libvirt,event_poll_remove_timeout,arg1)

/* LIBVIRT_EVENT_POLL_DISPATCH_TIMEOUT ( int timer) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_DISPATCH_TIMEOUT_ENABLED() __builtin_expect (event_poll_dispatch_timeout_semaphore, 0)
#define libvirt_event_poll_dispatch_timeout_semaphore event_poll_dispatch_timeout_semaphore
#else
#define LIBVIRT_EVENT_POLL_DISPATCH_TIMEOUT_ENABLED() __builtin_expect (libvirt_event_poll_dispatch_timeout_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_dispatch_timeout_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_DISPATCH_TIMEOUT(arg1) \
STAP_PROBE1(libvirt,event_poll_dispatch_timeout,arg1)

/* LIBVIRT_EVENT_POLL_PURGE_TIMEOUT ( int timer) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_PURGE_TIMEOUT_ENABLED() __builtin_expect (event_poll_purge_timeout_semaphore, 0)
#define libvirt_event_poll_purge_timeout_semaphore event_poll_purge_timeout_semaphore
#else
#define LIBVIRT_EVENT_POLL_PURGE_TIMEOUT_ENABLED() __builtin_expect (libvirt_event_poll_purge_timeout_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_purge_timeout_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_PURGE_TIMEOUT(arg1) \
STAP_PROBE1(libvirt,event_poll_purge_timeout,arg1)

/* LIBVIRT_EVENT_POLL_RUN ( int nfds, int timeout) */
#if defined STAP_SDT_V1
#define LIBVIRT_EVENT_POLL_RUN_ENABLED() __builtin_expect (event_poll_run_semaphore, 0)
#define libvirt_event_poll_run_semaphore event_poll_run_semaphore
#else
#define LIBVIRT_EVENT_POLL_RUN_ENABLED() __builtin_expect (libvirt_event_poll_run_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_event_poll_run_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_EVENT_POLL_RUN(arg1,arg2) \
STAP_PROBE2(libvirt,event_poll_run,arg1,arg2)

/* LIBVIRT_RPC_SOCKET_NEW ( void *sock, int refs, int fd, int errfd, int pid, const char *localAddr, const char *remoteAddr) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SOCKET_NEW_ENABLED() __builtin_expect (rpc_socket_new_semaphore, 0)
#define libvirt_rpc_socket_new_semaphore rpc_socket_new_semaphore
#else
#define LIBVIRT_RPC_SOCKET_NEW_ENABLED() __builtin_expect (libvirt_rpc_socket_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_socket_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SOCKET_NEW(arg1,arg2,arg3,arg4,arg5,arg6,arg7) \
STAP_PROBE7(libvirt,rpc_socket_new,arg1,arg2,arg3,arg4,arg5,arg6,arg7)

/* LIBVIRT_RPC_SOCKET_SEND_FD ( void *sock, int fd) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SOCKET_SEND_FD_ENABLED() __builtin_expect (rpc_socket_send_fd_semaphore, 0)
#define libvirt_rpc_socket_send_fd_semaphore rpc_socket_send_fd_semaphore
#else
#define LIBVIRT_RPC_SOCKET_SEND_FD_ENABLED() __builtin_expect (libvirt_rpc_socket_send_fd_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_socket_send_fd_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SOCKET_SEND_FD(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_socket_send_fd,arg1,arg2)

/* LIBVIRT_RPC_SOCKET_RECV_FD ( void *sock, int fd) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SOCKET_RECV_FD_ENABLED() __builtin_expect (rpc_socket_recv_fd_semaphore, 0)
#define libvirt_rpc_socket_recv_fd_semaphore rpc_socket_recv_fd_semaphore
#else
#define LIBVIRT_RPC_SOCKET_RECV_FD_ENABLED() __builtin_expect (libvirt_rpc_socket_recv_fd_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_socket_recv_fd_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SOCKET_RECV_FD(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_socket_recv_fd,arg1,arg2)

/* LIBVIRT_RPC_SOCKET_REF ( void *sock, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SOCKET_REF_ENABLED() __builtin_expect (rpc_socket_ref_semaphore, 0)
#define libvirt_rpc_socket_ref_semaphore rpc_socket_ref_semaphore
#else
#define LIBVIRT_RPC_SOCKET_REF_ENABLED() __builtin_expect (libvirt_rpc_socket_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_socket_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SOCKET_REF(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_socket_ref,arg1,arg2)

/* LIBVIRT_RPC_SOCKET_FREE ( void *sock, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SOCKET_FREE_ENABLED() __builtin_expect (rpc_socket_free_semaphore, 0)
#define libvirt_rpc_socket_free_semaphore rpc_socket_free_semaphore
#else
#define LIBVIRT_RPC_SOCKET_FREE_ENABLED() __builtin_expect (libvirt_rpc_socket_free_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_socket_free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SOCKET_FREE(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_socket_free,arg1,arg2)

/* LIBVIRT_RPC_SERVER_CLIENT_NEW ( void *client, int refs, void *sock) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_NEW_ENABLED() __builtin_expect (rpc_server_client_new_semaphore, 0)
#define libvirt_rpc_server_client_new_semaphore rpc_server_client_new_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_NEW_ENABLED() __builtin_expect (libvirt_rpc_server_client_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_NEW(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_server_client_new,arg1,arg2,arg3)

/* LIBVIRT_RPC_SERVER_CLIENT_REF ( void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_REF_ENABLED() __builtin_expect (rpc_server_client_ref_semaphore, 0)
#define libvirt_rpc_server_client_ref_semaphore rpc_server_client_ref_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_REF_ENABLED() __builtin_expect (libvirt_rpc_server_client_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_REF(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_server_client_ref,arg1,arg2)

/* LIBVIRT_RPC_SERVER_CLIENT_FREE ( void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_FREE_ENABLED() __builtin_expect (rpc_server_client_free_semaphore, 0)
#define libvirt_rpc_server_client_free_semaphore rpc_server_client_free_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_FREE_ENABLED() __builtin_expect (libvirt_rpc_server_client_free_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_FREE(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_server_client_free,arg1,arg2)

/* LIBVIRT_RPC_SERVER_CLIENT_MSG_TX_QUEUE ( void *client, int len, int prog, int vers, int proc, int type, int status, int serial) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_MSG_TX_QUEUE_ENABLED() __builtin_expect (rpc_server_client_msg_tx_queue_semaphore, 0)
#define libvirt_rpc_server_client_msg_tx_queue_semaphore rpc_server_client_msg_tx_queue_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_MSG_TX_QUEUE_ENABLED() __builtin_expect (libvirt_rpc_server_client_msg_tx_queue_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_msg_tx_queue_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_MSG_TX_QUEUE(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8) \
STAP_PROBE8(libvirt,rpc_server_client_msg_tx_queue,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8)

/* LIBVIRT_RPC_SERVER_CLIENT_MSG_RX ( void *client, int len, int prog, int vers, int proc, int type, int status, int serial) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_MSG_RX_ENABLED() __builtin_expect (rpc_server_client_msg_rx_semaphore, 0)
#define libvirt_rpc_server_client_msg_rx_semaphore rpc_server_client_msg_rx_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_MSG_RX_ENABLED() __builtin_expect (libvirt_rpc_server_client_msg_rx_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_msg_rx_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_MSG_RX(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8) \
STAP_PROBE8(libvirt,rpc_server_client_msg_rx,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8)

/* LIBVIRT_RPC_CLIENT_NEW ( void *client, int refs, void *sock) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_CLIENT_NEW_ENABLED() __builtin_expect (rpc_client_new_semaphore, 0)
#define libvirt_rpc_client_new_semaphore rpc_client_new_semaphore
#else
#define LIBVIRT_RPC_CLIENT_NEW_ENABLED() __builtin_expect (libvirt_rpc_client_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_client_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_CLIENT_NEW(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_client_new,arg1,arg2,arg3)

/* LIBVIRT_RPC_CLIENT_REF ( void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_CLIENT_REF_ENABLED() __builtin_expect (rpc_client_ref_semaphore, 0)
#define libvirt_rpc_client_ref_semaphore rpc_client_ref_semaphore
#else
#define LIBVIRT_RPC_CLIENT_REF_ENABLED() __builtin_expect (libvirt_rpc_client_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_client_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_CLIENT_REF(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_client_ref,arg1,arg2)

/* LIBVIRT_RPC_CLIENT_FREE ( void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_CLIENT_FREE_ENABLED() __builtin_expect (rpc_client_free_semaphore, 0)
#define libvirt_rpc_client_free_semaphore rpc_client_free_semaphore
#else
#define LIBVIRT_RPC_CLIENT_FREE_ENABLED() __builtin_expect (libvirt_rpc_client_free_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_client_free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_CLIENT_FREE(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_client_free,arg1,arg2)

/* LIBVIRT_RPC_CLIENT_MSG_TX_QUEUE ( void *client, int len, int prog, int vers, int proc, int type, int status, int serial) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_CLIENT_MSG_TX_QUEUE_ENABLED() __builtin_expect (rpc_client_msg_tx_queue_semaphore, 0)
#define libvirt_rpc_client_msg_tx_queue_semaphore rpc_client_msg_tx_queue_semaphore
#else
#define LIBVIRT_RPC_CLIENT_MSG_TX_QUEUE_ENABLED() __builtin_expect (libvirt_rpc_client_msg_tx_queue_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_client_msg_tx_queue_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_CLIENT_MSG_TX_QUEUE(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8) \
STAP_PROBE8(libvirt,rpc_client_msg_tx_queue,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8)

/* LIBVIRT_RPC_CLIENT_MSG_RX ( void *client, int len, int prog, int vers, int proc, int type, int status, int serial) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_CLIENT_MSG_RX_ENABLED() __builtin_expect (rpc_client_msg_rx_semaphore, 0)
#define libvirt_rpc_client_msg_rx_semaphore rpc_client_msg_rx_semaphore
#else
#define LIBVIRT_RPC_CLIENT_MSG_RX_ENABLED() __builtin_expect (libvirt_rpc_client_msg_rx_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_client_msg_rx_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_CLIENT_MSG_RX(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8) \
STAP_PROBE8(libvirt,rpc_client_msg_rx,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8)

/* LIBVIRT_RPC_SERVER_CLIENT_AUTH_ALLOW ( void *client, int authtype, const char *identity) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_ALLOW_ENABLED() __builtin_expect (rpc_server_client_auth_allow_semaphore, 0)
#define libvirt_rpc_server_client_auth_allow_semaphore rpc_server_client_auth_allow_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_ALLOW_ENABLED() __builtin_expect (libvirt_rpc_server_client_auth_allow_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_auth_allow_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_ALLOW(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_server_client_auth_allow,arg1,arg2,arg3)

/* LIBVIRT_RPC_SERVER_CLIENT_AUTH_DENY ( void *client, int authtype, const char *identity) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_DENY_ENABLED() __builtin_expect (rpc_server_client_auth_deny_semaphore, 0)
#define libvirt_rpc_server_client_auth_deny_semaphore rpc_server_client_auth_deny_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_DENY_ENABLED() __builtin_expect (libvirt_rpc_server_client_auth_deny_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_auth_deny_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_DENY(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_server_client_auth_deny,arg1,arg2,arg3)

/* LIBVIRT_RPC_SERVER_CLIENT_AUTH_FAIL ( void *client, int authtype) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_FAIL_ENABLED() __builtin_expect (rpc_server_client_auth_fail_semaphore, 0)
#define libvirt_rpc_server_client_auth_fail_semaphore rpc_server_client_auth_fail_semaphore
#else
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_FAIL_ENABLED() __builtin_expect (libvirt_rpc_server_client_auth_fail_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_server_client_auth_fail_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_SERVER_CLIENT_AUTH_FAIL(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_server_client_auth_fail,arg1,arg2)

/* LIBVIRT_RPC_TLS_CONTEXT_NEW ( void *ctxt, int refs, const char *cacert, const char *cacrl, const char *cert, const char *key, int sanityCheckCert, int requireValidCert, int isServer) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_CONTEXT_NEW_ENABLED() __builtin_expect (rpc_tls_context_new_semaphore, 0)
#define libvirt_rpc_tls_context_new_semaphore rpc_tls_context_new_semaphore
#else
#define LIBVIRT_RPC_TLS_CONTEXT_NEW_ENABLED() __builtin_expect (libvirt_rpc_tls_context_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_context_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_CONTEXT_NEW(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9) \
STAP_PROBE9(libvirt,rpc_tls_context_new,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9)

/* LIBVIRT_RPC_TLS_CONTEXT_REF ( void *ctxt, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_CONTEXT_REF_ENABLED() __builtin_expect (rpc_tls_context_ref_semaphore, 0)
#define libvirt_rpc_tls_context_ref_semaphore rpc_tls_context_ref_semaphore
#else
#define LIBVIRT_RPC_TLS_CONTEXT_REF_ENABLED() __builtin_expect (libvirt_rpc_tls_context_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_context_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_CONTEXT_REF(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_tls_context_ref,arg1,arg2)

/* LIBVIRT_RPC_TLS_CONTEXT_FREE ( void *ctxt, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_CONTEXT_FREE_ENABLED() __builtin_expect (rpc_tls_context_free_semaphore, 0)
#define libvirt_rpc_tls_context_free_semaphore rpc_tls_context_free_semaphore
#else
#define LIBVIRT_RPC_TLS_CONTEXT_FREE_ENABLED() __builtin_expect (libvirt_rpc_tls_context_free_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_context_free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_CONTEXT_FREE(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_tls_context_free,arg1,arg2)

/* LIBVIRT_RPC_TLS_CONTEXT_SESSION_ALLOW ( void *ctxt, void *sess, const char *dname) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_ALLOW_ENABLED() __builtin_expect (rpc_tls_context_session_allow_semaphore, 0)
#define libvirt_rpc_tls_context_session_allow_semaphore rpc_tls_context_session_allow_semaphore
#else
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_ALLOW_ENABLED() __builtin_expect (libvirt_rpc_tls_context_session_allow_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_context_session_allow_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_ALLOW(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_tls_context_session_allow,arg1,arg2,arg3)

/* LIBVIRT_RPC_TLS_CONTEXT_SESSION_DENY ( void *ctxt, void *sess, const char *dname) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_DENY_ENABLED() __builtin_expect (rpc_tls_context_session_deny_semaphore, 0)
#define libvirt_rpc_tls_context_session_deny_semaphore rpc_tls_context_session_deny_semaphore
#else
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_DENY_ENABLED() __builtin_expect (libvirt_rpc_tls_context_session_deny_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_context_session_deny_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_DENY(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_tls_context_session_deny,arg1,arg2,arg3)

/* LIBVIRT_RPC_TLS_CONTEXT_SESSION_FAIL ( void *ctxt, void *sess) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_FAIL_ENABLED() __builtin_expect (rpc_tls_context_session_fail_semaphore, 0)
#define libvirt_rpc_tls_context_session_fail_semaphore rpc_tls_context_session_fail_semaphore
#else
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_FAIL_ENABLED() __builtin_expect (libvirt_rpc_tls_context_session_fail_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_context_session_fail_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_CONTEXT_SESSION_FAIL(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_tls_context_session_fail,arg1,arg2)

/* LIBVIRT_RPC_TLS_SESSION_NEW ( void *sess, void *ctxt, int refs, const char *hostname, int isServer) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_SESSION_NEW_ENABLED() __builtin_expect (rpc_tls_session_new_semaphore, 0)
#define libvirt_rpc_tls_session_new_semaphore rpc_tls_session_new_semaphore
#else
#define LIBVIRT_RPC_TLS_SESSION_NEW_ENABLED() __builtin_expect (libvirt_rpc_tls_session_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_session_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_SESSION_NEW(arg1,arg2,arg3,arg4,arg5) \
STAP_PROBE5(libvirt,rpc_tls_session_new,arg1,arg2,arg3,arg4,arg5)

/* LIBVIRT_RPC_TLS_SESSION_REF ( void *sess, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_SESSION_REF_ENABLED() __builtin_expect (rpc_tls_session_ref_semaphore, 0)
#define libvirt_rpc_tls_session_ref_semaphore rpc_tls_session_ref_semaphore
#else
#define LIBVIRT_RPC_TLS_SESSION_REF_ENABLED() __builtin_expect (libvirt_rpc_tls_session_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_session_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_SESSION_REF(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_tls_session_ref,arg1,arg2)

/* LIBVIRT_RPC_TLS_SESSION_FREE ( void *sess, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_SESSION_FREE_ENABLED() __builtin_expect (rpc_tls_session_free_semaphore, 0)
#define libvirt_rpc_tls_session_free_semaphore rpc_tls_session_free_semaphore
#else
#define LIBVIRT_RPC_TLS_SESSION_FREE_ENABLED() __builtin_expect (libvirt_rpc_tls_session_free_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_session_free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_SESSION_FREE(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_tls_session_free,arg1,arg2)

/* LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_PASS ( void *sess) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_PASS_ENABLED() __builtin_expect (rpc_tls_session_handshake_pass_semaphore, 0)
#define libvirt_rpc_tls_session_handshake_pass_semaphore rpc_tls_session_handshake_pass_semaphore
#else
#define LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_PASS_ENABLED() __builtin_expect (libvirt_rpc_tls_session_handshake_pass_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_session_handshake_pass_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_PASS(arg1) \
STAP_PROBE1(libvirt,rpc_tls_session_handshake_pass,arg1)

/* LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_FAIL ( void *sess) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_FAIL_ENABLED() __builtin_expect (rpc_tls_session_handshake_fail_semaphore, 0)
#define libvirt_rpc_tls_session_handshake_fail_semaphore rpc_tls_session_handshake_fail_semaphore
#else
#define LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_FAIL_ENABLED() __builtin_expect (libvirt_rpc_tls_session_handshake_fail_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_tls_session_handshake_fail_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_TLS_SESSION_HANDSHAKE_FAIL(arg1) \
STAP_PROBE1(libvirt,rpc_tls_session_handshake_fail,arg1)

/* LIBVIRT_RPC_KEEPALIVE_NEW ( void *ka, void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_NEW_ENABLED() __builtin_expect (rpc_keepalive_new_semaphore, 0)
#define libvirt_rpc_keepalive_new_semaphore rpc_keepalive_new_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_NEW_ENABLED() __builtin_expect (libvirt_rpc_keepalive_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_NEW(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_keepalive_new,arg1,arg2,arg3)

/* LIBVIRT_RPC_KEEPALIVE_REF ( void *ka, void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_REF_ENABLED() __builtin_expect (rpc_keepalive_ref_semaphore, 0)
#define libvirt_rpc_keepalive_ref_semaphore rpc_keepalive_ref_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_REF_ENABLED() __builtin_expect (libvirt_rpc_keepalive_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_REF(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_keepalive_ref,arg1,arg2,arg3)

/* LIBVIRT_RPC_KEEPALIVE_FREE ( void *ka, void *client, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_FREE_ENABLED() __builtin_expect (rpc_keepalive_free_semaphore, 0)
#define libvirt_rpc_keepalive_free_semaphore rpc_keepalive_free_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_FREE_ENABLED() __builtin_expect (libvirt_rpc_keepalive_free_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_FREE(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,rpc_keepalive_free,arg1,arg2,arg3)

/* LIBVIRT_RPC_KEEPALIVE_START ( void *ka, void *client, int interval, int count) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_START_ENABLED() __builtin_expect (rpc_keepalive_start_semaphore, 0)
#define libvirt_rpc_keepalive_start_semaphore rpc_keepalive_start_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_START_ENABLED() __builtin_expect (libvirt_rpc_keepalive_start_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_START(arg1,arg2,arg3,arg4) \
STAP_PROBE4(libvirt,rpc_keepalive_start,arg1,arg2,arg3,arg4)

/* LIBVIRT_RPC_KEEPALIVE_STOP ( void *ka, void *client) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_STOP_ENABLED() __builtin_expect (rpc_keepalive_stop_semaphore, 0)
#define libvirt_rpc_keepalive_stop_semaphore rpc_keepalive_stop_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_STOP_ENABLED() __builtin_expect (libvirt_rpc_keepalive_stop_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_stop_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_STOP(arg1,arg2) \
STAP_PROBE2(libvirt,rpc_keepalive_stop,arg1,arg2)

/* LIBVIRT_RPC_KEEPALIVE_SEND ( void *ka, void *client, int prog, int vers, int proc) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_SEND_ENABLED() __builtin_expect (rpc_keepalive_send_semaphore, 0)
#define libvirt_rpc_keepalive_send_semaphore rpc_keepalive_send_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_SEND_ENABLED() __builtin_expect (libvirt_rpc_keepalive_send_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_send_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_SEND(arg1,arg2,arg3,arg4,arg5) \
STAP_PROBE5(libvirt,rpc_keepalive_send,arg1,arg2,arg3,arg4,arg5)

/* LIBVIRT_RPC_KEEPALIVE_RECEIVED ( void *ka, void *client, int prog, int vers, int proc) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_RECEIVED_ENABLED() __builtin_expect (rpc_keepalive_received_semaphore, 0)
#define libvirt_rpc_keepalive_received_semaphore rpc_keepalive_received_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_RECEIVED_ENABLED() __builtin_expect (libvirt_rpc_keepalive_received_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_received_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_RECEIVED(arg1,arg2,arg3,arg4,arg5) \
STAP_PROBE5(libvirt,rpc_keepalive_received,arg1,arg2,arg3,arg4,arg5)

/* LIBVIRT_RPC_KEEPALIVE_TIMEOUT ( void *ka, void *client, int coundToDeath, int idle) */
#if defined STAP_SDT_V1
#define LIBVIRT_RPC_KEEPALIVE_TIMEOUT_ENABLED() __builtin_expect (rpc_keepalive_timeout_semaphore, 0)
#define libvirt_rpc_keepalive_timeout_semaphore rpc_keepalive_timeout_semaphore
#else
#define LIBVIRT_RPC_KEEPALIVE_TIMEOUT_ENABLED() __builtin_expect (libvirt_rpc_keepalive_timeout_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_rpc_keepalive_timeout_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_RPC_KEEPALIVE_TIMEOUT(arg1,arg2,arg3,arg4) \
STAP_PROBE4(libvirt,rpc_keepalive_timeout,arg1,arg2,arg3,arg4)

/* LIBVIRT_QEMU_MONITOR_NEW ( void *mon, int refs, int fd) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_NEW_ENABLED() __builtin_expect (qemu_monitor_new_semaphore, 0)
#define libvirt_qemu_monitor_new_semaphore qemu_monitor_new_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_NEW_ENABLED() __builtin_expect (libvirt_qemu_monitor_new_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_NEW(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,qemu_monitor_new,arg1,arg2,arg3)

/* LIBVIRT_QEMU_MONITOR_REF ( void *mon, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_REF_ENABLED() __builtin_expect (qemu_monitor_ref_semaphore, 0)
#define libvirt_qemu_monitor_ref_semaphore qemu_monitor_ref_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_REF_ENABLED() __builtin_expect (libvirt_qemu_monitor_ref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_REF(arg1,arg2) \
STAP_PROBE2(libvirt,qemu_monitor_ref,arg1,arg2)

/* LIBVIRT_QEMU_MONITOR_UNREF ( void *mon, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_UNREF_ENABLED() __builtin_expect (qemu_monitor_unref_semaphore, 0)
#define libvirt_qemu_monitor_unref_semaphore qemu_monitor_unref_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_UNREF_ENABLED() __builtin_expect (libvirt_qemu_monitor_unref_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_unref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_UNREF(arg1,arg2) \
STAP_PROBE2(libvirt,qemu_monitor_unref,arg1,arg2)

/* LIBVIRT_QEMU_MONITOR_CLOSE ( void *monm, int refs) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_CLOSE_ENABLED() __builtin_expect (qemu_monitor_close_semaphore, 0)
#define libvirt_qemu_monitor_close_semaphore qemu_monitor_close_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_CLOSE_ENABLED() __builtin_expect (libvirt_qemu_monitor_close_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_close_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_CLOSE(arg1,arg2) \
STAP_PROBE2(libvirt,qemu_monitor_close,arg1,arg2)

/* LIBVIRT_QEMU_MONITOR_SEND_MSG ( void *mon, const char *msg, int fd) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_SEND_MSG_ENABLED() __builtin_expect (qemu_monitor_send_msg_semaphore, 0)
#define libvirt_qemu_monitor_send_msg_semaphore qemu_monitor_send_msg_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_SEND_MSG_ENABLED() __builtin_expect (libvirt_qemu_monitor_send_msg_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_send_msg_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_SEND_MSG(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,qemu_monitor_send_msg,arg1,arg2,arg3)

/* LIBVIRT_QEMU_MONITOR_RECV_REPLY ( void *mon, const char *reply) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_RECV_REPLY_ENABLED() __builtin_expect (qemu_monitor_recv_reply_semaphore, 0)
#define libvirt_qemu_monitor_recv_reply_semaphore qemu_monitor_recv_reply_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_RECV_REPLY_ENABLED() __builtin_expect (libvirt_qemu_monitor_recv_reply_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_recv_reply_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_RECV_REPLY(arg1,arg2) \
STAP_PROBE2(libvirt,qemu_monitor_recv_reply,arg1,arg2)

/* LIBVIRT_QEMU_MONITOR_RECV_EVENT ( void *mon, const char *event) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_RECV_EVENT_ENABLED() __builtin_expect (qemu_monitor_recv_event_semaphore, 0)
#define libvirt_qemu_monitor_recv_event_semaphore qemu_monitor_recv_event_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_RECV_EVENT_ENABLED() __builtin_expect (libvirt_qemu_monitor_recv_event_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_recv_event_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_RECV_EVENT(arg1,arg2) \
STAP_PROBE2(libvirt,qemu_monitor_recv_event,arg1,arg2)

/* LIBVIRT_QEMU_MONITOR_IO_PROCESS ( void *mon, const char *buf, unsigned int len) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_IO_PROCESS_ENABLED() __builtin_expect (qemu_monitor_io_process_semaphore, 0)
#define libvirt_qemu_monitor_io_process_semaphore qemu_monitor_io_process_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_IO_PROCESS_ENABLED() __builtin_expect (libvirt_qemu_monitor_io_process_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_io_process_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_IO_PROCESS(arg1,arg2,arg3) \
STAP_PROBE3(libvirt,qemu_monitor_io_process,arg1,arg2,arg3)

/* LIBVIRT_QEMU_MONITOR_IO_READ ( void *mon, const char *buf, unsigned int len, int ret, int errno) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_IO_READ_ENABLED() __builtin_expect (qemu_monitor_io_read_semaphore, 0)
#define libvirt_qemu_monitor_io_read_semaphore qemu_monitor_io_read_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_IO_READ_ENABLED() __builtin_expect (libvirt_qemu_monitor_io_read_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_io_read_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_IO_READ(arg1,arg2,arg3,arg4,arg5) \
STAP_PROBE5(libvirt,qemu_monitor_io_read,arg1,arg2,arg3,arg4,arg5)

/* LIBVIRT_QEMU_MONITOR_IO_WRITE ( void *mon, const char *buf, unsigned int len, int ret, int errno) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_IO_WRITE_ENABLED() __builtin_expect (qemu_monitor_io_write_semaphore, 0)
#define libvirt_qemu_monitor_io_write_semaphore qemu_monitor_io_write_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_IO_WRITE_ENABLED() __builtin_expect (libvirt_qemu_monitor_io_write_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_io_write_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_IO_WRITE(arg1,arg2,arg3,arg4,arg5) \
STAP_PROBE5(libvirt,qemu_monitor_io_write,arg1,arg2,arg3,arg4,arg5)

/* LIBVIRT_QEMU_MONITOR_IO_SEND_FD ( void *mon, int fd, int ret, int errno) */
#if defined STAP_SDT_V1
#define LIBVIRT_QEMU_MONITOR_IO_SEND_FD_ENABLED() __builtin_expect (qemu_monitor_io_send_fd_semaphore, 0)
#define libvirt_qemu_monitor_io_send_fd_semaphore qemu_monitor_io_send_fd_semaphore
#else
#define LIBVIRT_QEMU_MONITOR_IO_SEND_FD_ENABLED() __builtin_expect (libvirt_qemu_monitor_io_send_fd_semaphore, 0)
#endif
__extension__ extern unsigned short libvirt_qemu_monitor_io_send_fd_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define LIBVIRT_QEMU_MONITOR_IO_SEND_FD(arg1,arg2,arg3,arg4) \
STAP_PROBE4(libvirt,qemu_monitor_io_send_fd,arg1,arg2,arg3,arg4)

